//
// $Id: iflogging.idl 19 2006-07-09 23:49:21Z sdi2 $
//
// Description: Interface for logging
//

/* our datatypes & exceptions */
#include <types.idl>

[uuid(IF_LOGGING_ID)]
interface IF_LOGGING {

    void LogMessage( in logmessage_t message );

};
