/*
 * $Id: ifpci.idl 43 2006-07-13 17:54:16Z sdi2 $
 */
#include <types.idl>

typedef uint8_t pciconfig[64];

[uuid(IF_PCI_ID)]
interface IF_PCI {

	void ScanForDevice(in uint16_t vendorID, in uint16_t deviceID, out pciconfig config)
		raises(no_such_device);

};
