/*
 * $Id: pci.idl 19 2006-07-09 23:49:21Z sdi2 $
 */

#include <ifmemory.idl>
#include <iflocator.idl>
#include <iffile.idl>

interface pager : IF_MEMORY, IF_DIRECTORY, IF_ENUMERABLE, IF_FILE {

    /* Nothing more needed */
      
};
