/*
 * $Id: minixfs.idl 172 2006-07-26 15:00:01Z sdi2 $
 */

#include <iffile.idl>
#include <iflocator.idl>
#include <iffiledirectory.idl>

interface minixfs : IF_DIRECTORY, IF_FILEDIRECTORY, IF_ENUMERABLE, IF_FILE {

	/* Nothing more needed */

};
