Stxxl: io/benchmark_random_block_access.cpp File Reference
io/benchmark_random_block_access.cpp File Reference
#include <iomanip>
#include <vector>
#include <stxxl/io>
#include <stxxl/mng>
#include <unistd.h>
Defines
#define BLOCK_ALIGN 4096
#define KB (1024)
#define MB (1024 * 1024)
#define GB (1024 * 1024 * 1024)
#define run(bs) run_test<bs>(span, num_blocks, do_init, do_read, do_write)
Functions
void usage (const char *argv0)
template<unsigned BlockSize>
void run_test (stxxl::int64 span, stxxl::int64 num_blocks, bool do_init, bool do_read, bool do_write)
int main (int argc, char *argv[])
Define Documentation
#define BLOCK_ALIGN 4096
Definition at line 43 of file benchmark_random_block_access.cpp.
#define GB (1024 * 1024 * 1024)
Definition at line 48 of file benchmark_random_block_access.cpp.
#define KB (1024)
Definition at line 46 of file benchmark_random_block_access.cpp.
Referenced by main().
#define MB (1024 * 1024)
Definition at line 47 of file benchmark_random_block_access.cpp.
Referenced by main(), and run_test().
#define run (bs) run_test<bs>(span, num_blocks, do_init, do_read, do_write)
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
Definition at line 164 of file benchmark_random_block_access.cpp.
References block_size, KB, MB, run, and usage().
template<unsigned BlockSize> void run_test (stxxl::int64 span, stxxl::int64 num_blocks, bool do_init, bool do_read, bool do_write)
Definition at line 73 of file benchmark_random_block_access.cpp.
References stxxl::add_IEC_binary_multiplier(), stxxl::div_ceil(), MB, stxxl::random_shuffle(), STXXL_DEFAULT_ALLOC_STRATEGY, stxxl::STXXL_MIN(), stxxl::timestamp(), and stxxl::wait_all().
void usage (const char * argv0)
Definition at line 50 of file benchmark_random_block_access.cpp.