Stxxl: io/benchmark_disk_and_flash.cpp File Reference
io/benchmark_disk_and_flash.cpp File Reference
#include <iomanip>
#include <vector>
#include <stxxl/io>
#include <stxxl/aligned_alloc>
#include <unistd.h>
Defines
#define BLOCK_ALIGN 4096
#define KB (1024)
#define MB (1024 * 1024)
#define GB (1024 * 1024 * 1024)
Functions
void run (char *buffer, file **disks, stxxl::int64 offset, stxxl::int64 length, unsigned hdd_blocks, unsigned hdd_bytes, unsigned ssd_blocks, unsigned ssd_bytes, unsigned repeats)
void usage (const char *argv0)
int main (int argc, char *argv[])
Define Documentation
#define BLOCK_ALIGN 4096
Definition at line 33 of file benchmark_disk_and_flash.cpp.
#define GB (1024 * 1024 * 1024)
Definition at line 37 of file benchmark_disk_and_flash.cpp.
Referenced by main().
#define KB (1024)
Definition at line 35 of file benchmark_disk_and_flash.cpp.
Referenced by main().
#define MB (1024 * 1024)
Definition at line 36 of file benchmark_disk_and_flash.cpp.
Referenced by main(), and run().
Function Documentation
int main (int argc, char * argv[])
Definition at line 101 of file benchmark_disk_and_flash.cpp.
References buffer_size, GB, KB, MB, run(), stxxl::STXXL_MAX(), and usage().
void run (char * buffer, file ** disks, stxxl::int64 offset, stxxl::int64 length, unsigned hdd_blocks, unsigned hdd_bytes, unsigned ssd_blocks, unsigned ssd_bytes, unsigned repeats)
Definition at line 39 of file benchmark_disk_and_flash.cpp.
References stxxl::file::aread(), MB, stxxl::STXXL_MAX(), stxxl::timestamp(), and stxxl::wait_all().
Referenced by stxxl::stream::basic_runs_creator< Input_, CompareType_, BlockSize_, AllocStr_ >::compute_result(), stxxl::stream::runs_creator< use_push< ValueType_ >, CompareType_, BlockSize_, AllocStr_ >::compute_result(), stxxl::sort_local::create_runs(), stxxl::ksort_local::create_runs(), main(), and stxxl::stream::runs_creator< use_push< ValueType_ >, CompareType_, BlockSize_, AllocStr_ >::push().
void usage (const char * argv0)
Definition at line 93 of file benchmark_disk_and_flash.cpp.