Stxxl: io/benchmark_configured_disks.cpp File Reference
io/benchmark_configured_disks.cpp File Reference
#include <iomanip>
#include <vector>
#include <stxxl/io>
#include <stxxl/mng>
#include <unistd.h>
Defines
#define BLOCK_ALIGN 4096
#define POLL_DELAY 1000
#define CHECK_AFTER_READ 0
#define MB (1024 * 1024)
#define GB (1024 * 1024 * 1024)
Functions
void usage (const char *argv0)
int main (int argc, char *argv[])
Define Documentation
#define BLOCK_ALIGN 4096
Definition at line 42 of file benchmark_configured_disks.cpp.
Referenced by stxxl::request::check_alignment(), stxxl::mem_file::discard(), stxxl::fileperblock_file< base_file_type >::lock(), and stxxl::typed_block< RawSize_, T_, NRef_, InfoType_ >::typed_block().
#define CHECK_AFTER_READ 0
Definition at line 46 of file benchmark_configured_disks.cpp.
#define GB (1024 * 1024 * 1024)
Definition at line 50 of file benchmark_configured_disks.cpp.
Referenced by main().
#define MB (1024 * 1024)
Definition at line 49 of file benchmark_configured_disks.cpp.
Referenced by main().
#define POLL_DELAY 1000
Definition at line 44 of file benchmark_configured_disks.cpp.
Function Documentation
int main (int argc, char * argv[])
Examples:
algo/copy_and_sort_file.cpp, algo/sort_file.cpp, algo/test_bad_cmp.cpp, algo/test_ksort.cpp, algo/test_parallel_sort.cpp, algo/test_random_shuffle.cpp, algo/test_scan.cpp, algo/test_sort.cpp, algo/test_stable_ksort.cpp, containers/berkeley_db_benchmark.cpp, containers/leda_sm_pq_benchmark.cpp, containers/leda_sm_stack_benchmark.cpp, containers/pq_benchmark.cpp, containers/stack_benchmark.cpp, containers/test_many_stacks.cpp, containers/test_map_random.cpp, containers/test_matrix.cpp, containers/test_migr_stack.cpp, containers/test_pqueue.cpp, containers/test_sorter.cpp, containers/test_stack.cpp, containers/test_vector.cpp, containers/test_vector_export.cpp, containers/tpie_stack_benchmark.cpp, io/test_cancel.cpp, io/test_io.cpp, io/test_io_sizes.cpp, mng/test_buf_streams.cpp, mng/test_mng.cpp, mng/test_pool_pair.cpp, mng/test_prefetch_pool.cpp, mng/test_read_write_pool.cpp, mng/test_write_pool.cpp, stream/test_loop.cpp, stream/test_naive_transpose.cpp, stream/test_push_sort.cpp, stream/test_sorted_runs.cpp, and stream/test_stream.cpp.
Definition at line 60 of file benchmark_configured_disks.cpp.
References stxxl::add_IEC_binary_multiplier(), block_size, stxxl::div_ceil(), GB, MB, STXXL_DEFAULT_ALLOC_STRATEGY, stxxl::timestamp(), usage(), and stxxl::wait_all().
void usage (const char * argv0)
Definition at line 52 of file benchmark_configured_disks.cpp.
Referenced by main().