Stxxl: stxxl::serving_request Class Reference
stxxl::serving_request Class Reference
I/O primitives layer
Request which serves an I/O by calling the synchronous routine of the file.
#include <serving_request.h>
Public Member Functions
serving_request (const completion_handler &on_cmpl, file *f, void *buf, offset_type off, size_type b, request_type t)
const char * io_type () const
Identifies the type of I/O implementation.
Protected Member Functions
void serve ()
void completed ()
Detailed Description
Request which serves an I/O by calling the synchronous routine of the file.
Definition at line 26 of file serving_request.h.
Constructor & Destructor Documentation
stxxl::serving_request::serving_request (const completion_handler & on_cmpl, file * f, void * buf, offset_type off, size_type b, request_type t)
Definition at line 22 of file serving_request.cpp.
References stxxl::request::check_alignment().
Member Function Documentation
void stxxl::serving_request::completed () [protected, virtual]
Reimplemented from stxxl::request.
Definition at line 64 of file serving_request.cpp.
References stxxl::request_with_state::_state, stxxl::request_with_state::DONE, stxxl::request_with_state::READY2DIE, and stxxl::state< Tp >::set_to().
Referenced by serve().
const char * stxxl::serving_request::io_type () const [virtual]
Identifies the type of I/O implementation.
Returns:
pointer to null terminated string of characters, containing the name of I/O implementation
Implements stxxl::request_interface.
Definition at line 72 of file serving_request.cpp.
References stxxl::request::file_, and stxxl::file::io_type().
void stxxl::serving_request::serve () [protected, virtual]
Implements stxxl::request_interface.
Definition at line 39 of file serving_request.cpp.
References stxxl::request::buffer, stxxl::request::bytes, stxxl::request::check_nref(), completed(), stxxl::request::error_occured(), stxxl::request::file_, stxxl::file::get_allocator_id(), stxxl::request::offset, stxxl::request_interface::READ, stxxl::file::serve(), and stxxl::request::type.
The documentation for this class was generated from the following files:
include/stxxl/bits/io/serving_request.h
io/serving_request.cpp