Stxxl: stxxl::state< Tp > Class Template Reference
stxxl::state< Tp > Class Template Reference
#include <state.h>
Public Member Functions
state (value_type s)
~state ()
void set_to (value_type new_state)
void wait_for (value_type needed_state)
value_type operator() ()
Private Types
typedef Tp value_type
Private Attributes
pthread_mutex_t mutex
pthread_cond_t cond
value_type _state
Detailed Description
template<typename Tp = int>
class stxxl::state< Tp >
Definition at line 31 of file state.h.
Member Typedef Documentation
template<typename Tp = int> typedef Tp stxxl::state< Tp >::value_type [private]
Definition at line 33 of file state.h.
Constructor & Destructor Documentation
template<typename Tp = int> stxxl::state< Tp >::state (value_type s) [inline]
Definition at line 45 of file state.h.
template<typename Tp = int> stxxl::state< Tp >::~state () [inline]
Definition at line 53 of file state.h.
Member Function Documentation
template<typename Tp = int> value_type stxxl::state< Tp >::operator() () [inline]
Definition at line 98 of file state.h.
template<typename Tp = int> void stxxl::state< Tp >::set_to (value_type new_state) [inline]
Definition at line 67 of file state.h.
Referenced by stxxl::serving_request::completed(), stxxl::request_queue_impl_worker::start_thread(), and stxxl::request_queue_impl_worker::stop_thread().
template<typename Tp = int> void stxxl::state< Tp >::wait_for (value_type needed_state) [inline]
Definition at line 82 of file state.h.
Member Data Documentation
template<typename Tp = int> value_type stxxl::state< Tp >::_state [private]
Definition at line 42 of file state.h.
template<typename Tp = int> pthread_cond_t stxxl::state< Tp >::cond [private]
Definition at line 40 of file state.h.
template<typename Tp = int> pthread_mutex_t stxxl::state< Tp >::mutex [private]
Definition at line 39 of file state.h.
The documentation for this class was generated from the following file:
include/stxxl/bits/common/state.h