Stxxl: stxxl::double_blocked_index< size_type, modulo2, modulo1 > Class Template Reference
stxxl::double_blocked_index< size_type, modulo2, modulo1 > Class Template Reference
Internals
#include <vector.h>
Public Member Functions
double_blocked_index ()
double_blocked_index (size_type pos)
double_blocked_index (size_type block2, size_type block1, size_type offset)
double_blocked_index & operator= (size_type pos)
double_blocked_index & operator++ ()
double_blocked_index operator++ (int)
double_blocked_index & operator-- ()
double_blocked_index operator-- (int)
double_blocked_index operator+ (size_type addend) const
double_blocked_index & operator+= (size_type addend)
double_blocked_index operator- (size_type addend) const
size_type operator- (const double_blocked_index &dbi2) const
double_blocked_index & operator-= (size_type subtrahend)
bool operator== (const double_blocked_index &dbi2) const
bool operator!= (const double_blocked_index &dbi2) const
bool operator< (const double_blocked_index &dbi2) const
bool operator<= (const double_blocked_index &dbi2) const
bool operator> (const double_blocked_index &dbi2) const
bool operator>= (const double_blocked_index &dbi2) const
double_blocked_index & operator>>= (size_type shift)
size_type get_pos () const
const size_type & get_block2 () const
const size_type & get_block1 () const
const size_type & get_offset () const
Private Member Functions
void set (size_type pos)
Private Attributes
size_type pos
size_type block1
size_type block2
size_type offset
Static Private Attributes
static const size_type modulo12 = modulo1 * modulo2
Detailed Description
template<typename size_type, size_type modulo2, size_type modulo1>
class stxxl::double_blocked_index< size_type, modulo2, modulo1 >
Definition at line 45 of file vector.h.
Constructor & Destructor Documentation
template<typename size_type , size_type modulo2, size_type modulo1> stxxl::double_blocked_index< size_type, modulo2, modulo1 >::double_blocked_index () [inline]
Definition at line 67 of file vector.h.
template<typename size_type , size_type modulo2, size_type modulo1> stxxl::double_blocked_index< size_type, modulo2, modulo1 >::double_blocked_index (size_type pos) [inline]
Definition at line 72 of file vector.h.
template<typename size_type , size_type modulo2, size_type modulo1> stxxl::double_blocked_index< size_type, modulo2, modulo1 >::double_blocked_index (size_type block2, size_type block1, size_type offset) [inline]
Definition at line 77 of file vector.h.
Member Function Documentation
template<typename size_type , size_type modulo2, size_type modulo1> const size_type& stxxl::double_blocked_index< size_type, modulo2, modulo1 >::get_block1 () const [inline]
Definition at line 229 of file vector.h.
Referenced by stxxl::vector< ValueType >::bid(), and stxxl::vector< ValueType >::element().
template<typename size_type , size_type modulo2, size_type modulo1> const size_type& stxxl::double_blocked_index< size_type, modulo2, modulo1 >::get_block2 () const [inline]
Definition at line 224 of file vector.h.
Referenced by stxxl::vector< ValueType >::bid(), stxxl::vector< ValueType >::block_externally_updated(), and stxxl::vector< ValueType >::element().
template<typename size_type , size_type modulo2, size_type modulo1> const size_type& stxxl::double_blocked_index< size_type, modulo2, modulo1 >::get_offset () const [inline]
Definition at line 234 of file vector.h.
Referenced by stxxl::vector< ValueType >::element().
template<typename size_type , size_type modulo2, size_type modulo1> size_type stxxl::double_blocked_index< size_type, modulo2, modulo1 >::get_pos () const [inline]
Definition at line 219 of file vector.h.
Referenced by stxxl::vector< ValueType >::element().
template<typename size_type , size_type modulo2, size_type modulo1> bool stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator!= (const double_blocked_index< size_type, modulo2, modulo1 > & dbi2) const [inline]
Definition at line 188 of file vector.h.
References stxxl::double_blocked_index< size_type, modulo2, modulo1 >::pos.
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator+ (size_type addend) const [inline]
Definition at line 156 of file vector.h.
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index& stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator++ () [inline]
Definition at line 95 of file vector.h.
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator++ (int) [inline]
Definition at line 118 of file vector.h.
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index& stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator+= (size_type addend) [inline]
Definition at line 161 of file vector.h.
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator- (size_type addend) const [inline]
Definition at line 167 of file vector.h.
template<typename size_type , size_type modulo2, size_type modulo1> size_type stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator- (const double_blocked_index< size_type, modulo2, modulo1 > & dbi2) const [inline]
Definition at line 172 of file vector.h.
References stxxl::double_blocked_index< size_type, modulo2, modulo1 >::pos.
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index& stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator-- () [inline]
Definition at line 126 of file vector.h.
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator-- (int) [inline]
Definition at line 149 of file vector.h.
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index& stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator-= (size_type subtrahend) [inline]
Definition at line 177 of file vector.h.
template<typename size_type , size_type modulo2, size_type modulo1> bool stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator< (const double_blocked_index< size_type, modulo2, modulo1 > & dbi2) const [inline]
Definition at line 193 of file vector.h.
References stxxl::double_blocked_index< size_type, modulo2, modulo1 >::pos.
template<typename size_type , size_type modulo2, size_type modulo1> bool stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator<= (const double_blocked_index< size_type, modulo2, modulo1 > & dbi2) const [inline]
Definition at line 198 of file vector.h.
References stxxl::double_blocked_index< size_type, modulo2, modulo1 >::pos.
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index& stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator= (size_type pos) [inline]
Definition at line 88 of file vector.h.
template<typename size_type , size_type modulo2, size_type modulo1> bool stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator== (const double_blocked_index< size_type, modulo2, modulo1 > & dbi2) const [inline]
Definition at line 183 of file vector.h.
References stxxl::double_blocked_index< size_type, modulo2, modulo1 >::pos.
template<typename size_type , size_type modulo2, size_type modulo1> bool stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator> (const double_blocked_index< size_type, modulo2, modulo1 > & dbi2) const [inline]
Definition at line 203 of file vector.h.
References stxxl::double_blocked_index< size_type, modulo2, modulo1 >::pos.
template<typename size_type , size_type modulo2, size_type modulo1> bool stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator>= (const double_blocked_index< size_type, modulo2, modulo1 > & dbi2) const [inline]
Definition at line 208 of file vector.h.
References stxxl::double_blocked_index< size_type, modulo2, modulo1 >::pos.
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index& stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator>>= (size_type shift) [inline]
Definition at line 213 of file vector.h.
template<typename size_type , size_type modulo2, size_type modulo1> void stxxl::double_blocked_index< size_type, modulo2, modulo1 >::set (size_type pos) [inline, private]
Invariant:
block2 * modulo12 + block1 * modulo1 + offset == pos && 0 <= block1 < modulo2 && 0 <= offset < modulo1
Definition at line 53 of file vector.h.
Member Data Documentation
template<typename size_type , size_type modulo2, size_type modulo1> size_type stxxl::double_blocked_index< size_type, modulo2, modulo1 >::block1 [private]
Definition at line 49 of file vector.h.
template<typename size_type , size_type modulo2, size_type modulo1> size_type stxxl::double_blocked_index< size_type, modulo2, modulo1 >::block2 [private]
Definition at line 49 of file vector.h.
template<typename size_type , size_type modulo2, size_type modulo1> const size_type stxxl::double_blocked_index< size_type, modulo2, modulo1 >::modulo12 = modulo1 * modulo2 [static, private]
Definition at line 47 of file vector.h.
template<typename size_type , size_type modulo2, size_type modulo1> size_type stxxl::double_blocked_index< size_type, modulo2, modulo1 >::offset [private]
Definition at line 49 of file vector.h.
template<typename size_type , size_type modulo2, size_type modulo1> size_type stxxl::double_blocked_index< size_type, modulo2, modulo1 >::pos [private]
Definition at line 49 of file vector.h.
Referenced by stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator!=(), stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator-(), stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator<(), stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator<=(), stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator==(), stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator>(), and stxxl::double_blocked_index< size_type, modulo2, modulo1 >::operator>=().
The documentation for this class was generated from the following file:
include/stxxl/bits/containers/vector.h