Stxxl: stxxl::scoped_mutex_lock Class Reference
stxxl::scoped_mutex_lock Class Reference
Aquire a lock that's valid until the end of scope.
#include <mutex.h>
Public Member Functions
scoped_mutex_lock (mutex &mtx_)
~scoped_mutex_lock ()
void lock ()
void unlock ()
Private Attributes
mutex & mtx
bool is_locked
Detailed Description
Aquire a lock that's valid until the end of scope.
Definition at line 82 of file mutex.h.
Constructor & Destructor Documentation
stxxl::scoped_mutex_lock::scoped_mutex_lock (mutex & mtx_) [inline]
Definition at line 88 of file mutex.h.
stxxl::scoped_mutex_lock::~scoped_mutex_lock () [inline]
Definition at line 93 of file mutex.h.
Member Function Documentation
void stxxl::scoped_mutex_lock::lock () [inline]
Definition at line 98 of file mutex.h.
void stxxl::scoped_mutex_lock::unlock () [inline]
Definition at line 106 of file mutex.h.
Referenced by stxxl::DiskAllocator::new_blocks(), stxxl::request_queue_impl_1q::worker(), and stxxl::request_queue_impl_qwqr::worker().
Member Data Documentation
bool stxxl::scoped_mutex_lock::is_locked [private]
Definition at line 85 of file mutex.h.
mutex& stxxl::scoped_mutex_lock::mtx [private]
Definition at line 84 of file mutex.h.
The documentation for this class was generated from the following file:
include/stxxl/bits/common/mutex.h