Stxxl: stxxl::element_block< T, Size_ > Class Template Reference
stxxl::element_block< T, Size_ > Class Template Reference
Contains data elements for stxxl::typed_block , not intended for direct use.
#include <typed_block.h>
Public Types
enum { size = Size_ }
typedef T type
typedef T value_type
typedef T & reference
typedef const T & const_reference
typedef type * pointer
typedef pointer iterator
typedef const type * const_iterator
Public Member Functions
element_block ()
reference operator[] (int i)
An operator to access elements in the block.
iterator begin ()
Returns iterator pointing to the first element.
const_iterator begin () const
Returns const_iterator pointing to the first element.
const_iterator cbegin () const
Returns const_iterator pointing to the first element.
iterator end ()
Returns iterator pointing to the end element.
const_iterator end () const
Returns const_iterator pointing to the end element.
const_iterator cend () const
Returns const_iterator pointing to the end element.
Public Attributes
T elem [size]
Array of elements of type T.
Detailed Description
template<class T, unsigned Size_>
class stxxl::element_block< T, Size_ >
Contains data elements for stxxl::typed_block , not intended for direct use.
Definition at line 53 of file typed_block.h.
Member Typedef Documentation
template<class T, unsigned Size_> typedef const type* stxxl::element_block< T, Size_ >::const_iterator
Reimplemented in stxxl::typed_block< RawSize_, T_, NRef_, InfoType_ >.
Definition at line 62 of file typed_block.h.
template<class T, unsigned Size_> typedef const T& stxxl::element_block< T, Size_ >::const_reference
Reimplemented in stxxl::typed_block< RawSize_, T_, NRef_, InfoType_ >.
Definition at line 59 of file typed_block.h.
template<class T, unsigned Size_> typedef pointer stxxl::element_block< T, Size_ >::iterator
Reimplemented in stxxl::typed_block< RawSize_, T_, NRef_, InfoType_ >.
Definition at line 61 of file typed_block.h.
template<class T, unsigned Size_> typedef type* stxxl::element_block< T, Size_ >::pointer
Reimplemented in stxxl::typed_block< RawSize_, T_, NRef_, InfoType_ >.
Definition at line 60 of file typed_block.h.
template<class T, unsigned Size_> typedef T& stxxl::element_block< T, Size_ >::reference
Reimplemented in stxxl::typed_block< RawSize_, T_, NRef_, InfoType_ >.
Definition at line 58 of file typed_block.h.
template<class T, unsigned Size_> typedef T stxxl::element_block< T, Size_ >::type
Definition at line 56 of file typed_block.h.
template<class T, unsigned Size_> typedef T stxxl::element_block< T, Size_ >::value_type
Reimplemented in stxxl::typed_block< RawSize_, T_, NRef_, InfoType_ >.
Definition at line 57 of file typed_block.h.
Member Enumeration Documentation
template<class T, unsigned Size_> anonymous enum
Enumerator:
size
number of elements in the block
Definition at line 64 of file typed_block.h.
Constructor & Destructor Documentation
template<class T, unsigned Size_> stxxl::element_block< T, Size_ >::element_block () [inline]
Definition at line 72 of file typed_block.h.
Member Function Documentation
template<class T, unsigned Size_> iterator stxxl::element_block< T, Size_ >::begin () [inline]
Returns iterator pointing to the first element.
Definition at line 81 of file typed_block.h.
Referenced by stxxl::btree::normal_leaf< KeyType_, DataType_, KeyCmp_, RawSize_, BTreeType >::balance(), stxxl::btree::normal_node< KeyType_, KeyCmp_, RawSize_, BTreeType >::balance(), stxxl::stream::basic_runs_creator< Input_, CompareType_, BlockSize_, AllocStr_ >::compute_result(), stxxl::btree::btree< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::erase(), stxxl::btree::normal_leaf< KeyType_, DataType_, KeyCmp_, RawSize_, BTreeType >::fuse(), stxxl::btree::normal_node< KeyType_, KeyCmp_, RawSize_, BTreeType >::fuse(), stxxl::btree::normal_node< KeyType_, KeyCmp_, RawSize_, BTreeType >::insert(), stxxl::btree::btree< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::insert_into_root(), and stxxl::btree::normal_leaf< KeyType_, DataType_, KeyCmp_, RawSize_, BTreeType >::split().
template<class T, unsigned Size_> const_iterator stxxl::element_block< T, Size_ >::begin () const [inline]
Returns const_iterator pointing to the first element.
Definition at line 87 of file typed_block.h.
template<class T, unsigned Size_> const_iterator stxxl::element_block< T, Size_ >::cbegin () const [inline]
Returns const_iterator pointing to the first element.
Definition at line 93 of file typed_block.h.
template<class T, unsigned Size_> const_iterator stxxl::element_block< T, Size_ >::cend () const [inline]
Returns const_iterator pointing to the end element.
Definition at line 111 of file typed_block.h.
template<class T, unsigned Size_> iterator stxxl::element_block< T, Size_ >::end () [inline]
Returns iterator pointing to the end element.
Definition at line 99 of file typed_block.h.
template<class T, unsigned Size_> const_iterator stxxl::element_block< T, Size_ >::end () const [inline]
Returns const_iterator pointing to the end element.
Definition at line 105 of file typed_block.h.
template<class T, unsigned Size_> reference stxxl::element_block< T, Size_ >::operator[] (int i) [inline]
An operator to access elements in the block.
Definition at line 75 of file typed_block.h.
Member Data Documentation
template<class T, unsigned Size_> T stxxl::element_block< T, Size_ >::elem[size]
Array of elements of type T.
Definition at line 70 of file typed_block.h.
The documentation for this class was generated from the following file:
include/stxxl/bits/mng/typed_block.h