Stxxl: stxxl::request_ptr Class Reference
stxxl::request_ptr Class Reference
I/O primitives layer
Implemented as reference counting smart pointer.
#include <request_ptr.h>
Public Member Functions
request_ptr (request *ptr_=NULL)
Constructs an request_ptr from request pointer.
request_ptr (const request_ptr &p)
Constructs an request_ptr from a request_ptr object.
~request_ptr ()
Destructor.
request_ptr & operator= (const request_ptr &p)
Assignment operator from request_ptr object.
request_ptr & operator= (request *p)
Assignment operator from request pointer.
request & operator* () const
"Star" operator
request * operator-> () const
"Arrow" operator
bool operator== (const request_ptr &rp2) const
request * get () const
Access to owned request object (synonym for operator->())
bool valid () const
Returns true if object is initialized.
bool empty () const
Returns true if object is not initialized.
Private Member Functions
void add_ref ()
void sub_ref ()
Private Attributes
request * ptr
Detailed Description
Implemented as reference counting smart pointer.
Examples:
algo/sort_file.cpp, io/test_cancel.cpp, io/test_io.cpp, io/test_io_sizes.cpp, and mng/test_mng.cpp.
Definition at line 34 of file request_ptr.h.
Constructor & Destructor Documentation
stxxl::request_ptr::request_ptr (request * ptr_ = NULL) [inline]
Constructs an request_ptr from request pointer.
Definition at line 63 of file request_ptr.h.
References STXXL_VERBOSE_request_ptr.
stxxl::request_ptr::request_ptr (const request_ptr & p) [inline]
Constructs an request_ptr from a request_ptr object.
Definition at line 69 of file request_ptr.h.
References STXXL_VERBOSE_request_ptr.
stxxl::request_ptr::~request_ptr () [inline]
Destructor.
Definition at line 75 of file request_ptr.h.
References STXXL_VERBOSE_request_ptr.
Member Function Documentation
void stxxl::request_ptr::add_ref () [inline, private]
Definition at line 37 of file request_ptr.h.
References stxxl::request::add_ref().
bool stxxl::request_ptr::empty () const [inline]
Returns true if object is not initialized.
Definition at line 131 of file request_ptr.h.
Referenced by stxxl::request_queue_impl_1q::add_request(), stxxl::request_queue_impl_qwqr::add_request(), stxxl::request_queue_impl_1q::cancel_request(), and stxxl::request_queue_impl_qwqr::cancel_request().
request* stxxl::request_ptr::get () const [inline]
Access to owned request object (synonym for operator->())
Returns:
reference to owned request object
Warning:
Creation another request_ptr from the returned request or deletion causes unpredictable behaviour. Do not do that!
Definition at line 125 of file request_ptr.h.
Referenced by stxxl::request_queue_impl_qwqr::add_request(), and stxxl::request_queue_impl_qwqr::cancel_request().
request& stxxl::request_ptr::operator* () const [inline]
"Star" operator
Returns:
reference to owned request object
Definition at line 103 of file request_ptr.h.
request* stxxl::request_ptr::operator-> () const [inline]
"Arrow" operator
Returns:
pointer to owned request object
Definition at line 110 of file request_ptr.h.
request_ptr& stxxl::request_ptr::operator= (const request_ptr & p) [inline]
Assignment operator from request_ptr object.
Returns:
reference to itself
Definition at line 82 of file request_ptr.h.
References ptr.
request_ptr& stxxl::request_ptr::operator= (request * p) [inline]
Assignment operator from request pointer.
Returns:
reference to itself
Definition at line 89 of file request_ptr.h.
References STXXL_VERBOSE_request_ptr.
bool stxxl::request_ptr::operator== (const request_ptr & rp2) const [inline]
Definition at line 116 of file request_ptr.h.
References ptr.
void stxxl::request_ptr::sub_ref () [inline, private]
Definition at line 44 of file request_ptr.h.
References STXXL_VERBOSE_request_ptr.
bool stxxl::request_ptr::valid () const [inline]
Returns true if object is initialized.
Definition at line 128 of file request_ptr.h.
Referenced by stxxl::swappable_block< ValueType, BlockSideLength *BlockSideLength >::clean_sync(), stxxl::block_scheduler< SwappableBlockType >::flush(), and stxxl::block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::schedule_write().
Member Data Documentation
request* stxxl::request_ptr::ptr [private]
Definition at line 36 of file request_ptr.h.
Referenced by operator=(), and operator==().
The documentation for this class was generated from the following file:
include/stxxl/bits/io/request_ptr.h