Stxxl: stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ > Class Template Reference
stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ > Class Template Reference
Internals
External vector container.
#include <vector.h>
Public Types
enum constants { block_size = BlkSize_, page_size = PgSz_, on_disk = -1 }
typedef Tp_ value_type
typedef value_type & reference
typedef const value_type & const_reference
typedef value_type * pointer
typedef SzTp_ size_type
typedef stxxl::int64 difference_type
typedef const value_type * const_pointer
typedef PgTp_ pager_type
typedef AllocStr_ alloc_strategy_type
typedef vector_iterator
< value_type,
alloc_strategy_type, size_type,
difference_type, block_size,
pager_type, page_size > iterator
typedef const_vector_iterator
< value_type,
alloc_strategy_type, size_type,
difference_type, block_size,
pager_type, page_size > const_iterator
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
typedef bid_vector< block_size > bids_container_type
typedef
bids_container_type::iterator bids_container_iterator
typedef
bids_container_type::const_iterator const_bids_container_iterator
typedef typed_block< BlkSize_,
Tp_ > block_type
typedef double_blocked_index
< SzTp_, PgSz_,
block_type::size > blocked_index_type
Public Member Functions
vector (size_type n=0, unsigned_type npages=pager_type().size())
Constructs external vector.
void swap (vector &obj)
void allocate_page_cache () const
void deallocate_page_cache () const
size_type capacity () const
size_type raw_capacity () const
Returns the number of bytes that the vector has allocated on disks.
void reserve (size_type n)
void resize (size_type n)
void resize (size_type n, bool shrink_capacity)
void clear ()
void push_back (const_reference obj)
void pop_back ()
reference back ()
reference front ()
const_reference back () const
const_reference front () const
vector (file *from, size_type size=size_type(-1), size_type npages=pager_type().size())
Construct vector from a file.
vector (const vector &obj)
vector & operator= (const vector &obj)
size_type size () const
bool empty () const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
const_iterator end () const
const_iterator cend () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
const_reverse_iterator crbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_reverse_iterator crend () const
reference operator[] (size_type offset)
const_reference operator[] (size_type offset) const
bool is_element_cached (size_type offset) const
void flush () const
~vector ()
void export_files (std::string filename_prefix)
Export data such that it is persistent on the file system. Resulting files will be numbered ascending.
file * get_file () const
Get the file associated with this vector, or NULL.
template<typename ForwardIterator >
void set_content (const ForwardIterator &bid_begin, const ForwardIterator &bid_end, size_type n)
Set the blocks and the size of this container explicitly. The vector must be completely empty before.
int_type numpages () const
Number of pages used by the pager.
Private Types
enum { valid_on_disk = 0, uninitialized = 1, dirty = 2 }
Private Member Functions
size_type size_from_file_length (stxxl::uint64 file_length) const
stxxl::uint64 file_length () const
void _resize (size_type n)
void _resize_shrink_capacity (size_type n)
bids_container_iterator bid (const size_type &offset)
bids_container_iterator bid (const blocked_index_type &offset)
const_bids_container_iterator bid (const size_type &offset) const
const_bids_container_iterator bid (const blocked_index_type &offset) const
void read_page (int_type page_no, int_type cache_slot) const
void write_page (int_type page_no, int_type cache_slot) const
reference element (size_type offset)
reference element (const blocked_index_type &offset)
void page_externally_updated (unsigned_type page_no) const
void block_externally_updated (size_type offset) const
void block_externally_updated (const blocked_index_type &offset) const
Private Attributes
alloc_strategy_type alloc_strategy
size_type _size
bids_container_type _bids
pager_type pager
std::vector< unsigned char > _page_status
std::vector< int_type > _page_to_slot
simple_vector< int_type > _slot_to_page
std::queue< int_type > _free_slots
simple_vector< block_type > * _cache
file * _from
block_manager * bm
config * cfg
bool exported
Detailed Description
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64>
class stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >
External vector container.
For semantics of the methods see documentation of the STL std::vector
Template Parameters:
Tp_ type of contained objects (POD with no references to internal memory)
PgSz_ number of blocks in a page
PgTp_ pager type, random_pager<x> or lru_pager<x>, where x is the default number of pages, default is lru_pager<8>
BlkSize_ external block size in bytes, default is 2 MiB
AllocStr_ one of allocation strategies: striping , RC , SR , or FR default is RC
Memory consumption: BlkSize_*x*PgSz_ bytes
Warning:
Do not store references to the elements of an external vector. Such references might be invalidated during any following access to elements of the vector
Examples:
algo/copy_and_sort_file.cpp, algo/sort_file.cpp, algo/test_bad_cmp.cpp, algo/test_ksort.cpp, algo/test_parallel_sort.cpp, algo/test_random_shuffle.cpp, algo/test_scan.cpp, algo/test_sort.cpp, algo/test_stable_ksort.cpp, containers/test_vector.cpp, containers/test_vector_export.cpp, stream/test_naive_transpose.cpp, stream/test_push_sort.cpp, stream/test_sorted_runs.cpp, and stream/test_stream.cpp.
Definition at line 735 of file vector.h.
Member Typedef Documentation
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> typedef AllocStr_ stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::alloc_strategy_type
Definition at line 747 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> typedef bids_container_type::iterator stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::bids_container_iterator
Definition at line 765 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> typedef bid_vector<block_size> stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::bids_container_type
Definition at line 764 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> typedef typed_block<BlkSize_, Tp_> stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::block_type
Definition at line 768 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> typedef double_blocked_index<SzTp_, PgSz_, block_type::size> stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::blocked_index_type
Definition at line 769 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> typedef bids_container_type::const_iterator stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::const_bids_container_iterator
Definition at line 766 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> typedef const_vector_iterator<value_type, alloc_strategy_type, size_type, difference_type, block_size, pager_type, page_size> stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::const_iterator
Definition at line 759 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> typedef const value_type* stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::const_pointer
Definition at line 744 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> typedef const value_type& stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::const_reference
Definition at line 740 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> typedef std::reverse_iterator<const_iterator> stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::const_reverse_iterator
Definition at line 762 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> typedef stxxl::int64 stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::difference_type
Definition at line 743 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> typedef vector_iterator<value_type, alloc_strategy_type, size_type, difference_type, block_size, pager_type, page_size> stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::iterator
Definition at line 756 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> typedef PgTp_ stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::pager_type
Definition at line 746 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> typedef value_type* stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::pointer
Definition at line 741 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> typedef value_type& stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::reference
Definition at line 739 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> typedef std::reverse_iterator<iterator> stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::reverse_iterator
Definition at line 761 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> typedef SzTp_ stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::size_type
Reimplemented in stxxl::row_vector< ValueType >, and stxxl::column_vector< ValueType >.
Definition at line 742 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> typedef Tp_ stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::value_type
Definition at line 738 of file vector.h.
Member Enumeration Documentation
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> anonymous enum [private]
Enumerator:
valid_on_disk
uninitialized
dirty
Definition at line 777 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> enum stxxl::vector::constants
Enumerator:
block_size
page_size
on_disk
Definition at line 749 of file vector.h.
Constructor & Destructor Documentation
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::vector (size_type n = 0, unsigned_type npages = pager_type().size()) [inline]
Constructs external vector.
Parameters:
n Number of elements.
npages Number of cached pages.
Definition at line 814 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::vector (file * from, size_type size = size_type(-1), size_type npages = pager_type ().size ()) [inline]
Construct vector from a file.
Parameters:
from file to be constructed from
size Number of elements.
npages Number of cached pages.
Warning:
Only one vector can be assigned to a particular (physical) file. The block size of the vector must be a multiple of the element size sizeof(Tp_) and the page size (4096).
Definition at line 1027 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::vector (const vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ > & obj) [inline]
Definition at line 1074 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::~vector () [inline]
Definition at line 1218 of file vector.h.
Member Function Documentation
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> void stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::_resize (size_type n) [inline, private]
Definition at line 928 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> void stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::_resize_shrink_capacity (size_type n) [inline, private]
Definition at line 945 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> void stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::allocate_page_cache () const [inline]
Definition at line 858 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> reference stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::back () [inline]
Definition at line 1003 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> const_reference stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::back () const [inline]
Definition at line 1011 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> iterator stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::begin () [inline]
Examples:
algo/test_parallel_sort.cpp, and stream/test_stream.cpp.
Definition at line 1126 of file vector.h.
Referenced by checksum(), linear_sort_normal(), linear_sort_streamed(), main(), run_bdb_btree_big(), run_stxxl_map_big(), stxxl::column_vector< ValueType >::set_zero(), stxxl::row_vector< ValueType >::set_zero(), short_test(), test(), and stxxl::vector< ValueType >::vector().
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> const_iterator stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::begin () const [inline]
Definition at line 1130 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> bids_container_iterator stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::bid (const size_type & offset) [inline, private]
Definition at line 1301 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> bids_container_iterator stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::bid (const blocked_index_type & offset) [inline, private]
Definition at line 1307 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> const_bids_container_iterator stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::bid (const size_type & offset) const [inline, private]
Definition at line 1313 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> const_bids_container_iterator stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::bid (const blocked_index_type & offset) const [inline, private]
Definition at line 1319 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> void stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::block_externally_updated (size_type offset) const [inline, private]
Definition at line 1435 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> void stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::block_externally_updated (const blocked_index_type & offset) const [inline, private]
Definition at line 1440 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> size_type stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::capacity () const [inline]
Definition at line 873 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> const_iterator stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::cbegin () const [inline]
Definition at line 1134 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> const_iterator stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::cend () const [inline]
Definition at line 1146 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> void stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::clear () [inline]
Definition at line 975 of file vector.h.
Referenced by main().
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> const_reverse_iterator stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::crbegin () const [inline]
Definition at line 1159 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> const_reverse_iterator stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::crend () const [inline]
Definition at line 1171 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> void stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::deallocate_page_cache () const [inline]
Definition at line 866 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> reference stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::element (size_type offset) [inline, private]
Definition at line 1363 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> reference stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::element (const blocked_index_type & offset) [inline, private]
Definition at line 1371 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> bool stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::empty () const [inline]
Definition at line 1122 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> iterator stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::end () [inline]
Examples:
algo/test_parallel_sort.cpp, and stream/test_stream.cpp.
Definition at line 1138 of file vector.h.
Referenced by checksum(), linear_sort_normal(), linear_sort_streamed(), main(), run_stxxl_map_big(), stxxl::column_vector< ValueType >::set_zero(), stxxl::row_vector< ValueType >::set_zero(), test(), and stxxl::vector< ValueType >::vector().
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> const_iterator stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::end () const [inline]
Definition at line 1142 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> void stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::export_files (std::string filename_prefix) [inline]
Export data such that it is persistent on the file system. Resulting files will be numbered ascending.
Examples:
containers/test_vector_export.cpp.
Definition at line 1258 of file vector.h.
Referenced by main().
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> stxxl::uint64 stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::file_length () const [inline, private]
Definition at line 796 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> void stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::flush () const [inline]
Examples:
containers/test_vector_export.cpp.
Definition at line 1190 of file vector.h.
Referenced by main(), and short_test().
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> reference stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::front () [inline]
Definition at line 1007 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> const_reference stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::front () const [inline]
Definition at line 1015 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> file* stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::get_file () const [inline]
Get the file associated with this vector, or NULL.
Definition at line 1275 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> bool stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::is_element_cached (size_type offset) const [inline]
Definition at line 1185 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> int_type stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::numpages () const [inline]
Number of pages used by the pager.
Definition at line 1295 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> vector& stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::operator= (const vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ > & obj) [inline]
Definition at line 1108 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> reference stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::operator[] (size_type offset) [inline]
Definition at line 1176 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> const_reference stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::operator[] (size_type offset) const [inline]
Definition at line 1180 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> void stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::page_externally_updated (unsigned_type page_no) const [inline, private]
Definition at line 1421 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> void stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::pop_back () [inline]
Definition at line 998 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> void stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::push_back (const_reference obj) [inline]
Definition at line 992 of file vector.h.
Referenced by main().
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> size_type stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::raw_capacity () const [inline]
Returns the number of bytes that the vector has allocated on disks.
Definition at line 878 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> reverse_iterator stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::rbegin () [inline]
Definition at line 1151 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> const_reverse_iterator stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::rbegin () const [inline]
Definition at line 1155 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> void stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::read_page (int_type page_no, int_type cache_slot) const [inline, private]
Definition at line 1326 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> reverse_iterator stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::rend () [inline]
Definition at line 1163 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> const_reverse_iterator stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::rend () const [inline]
Definition at line 1167 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> void stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::reserve (size_type n) [inline]
Definition at line 883 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> void stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::resize (size_type n) [inline]
Examples:
stream/test_stream.cpp.
Definition at line 914 of file vector.h.
Referenced by main(), and test_write().
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> void stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::resize (size_type n, bool shrink_capacity) [inline]
Definition at line 919 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> template<typename ForwardIterator > void stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::set_content (const ForwardIterator & bid_begin, const ForwardIterator & bid_end, size_type n) [inline]
Set the blocks and the size of this container explicitly. The vector must be completely empty before.
Definition at line 1283 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> size_type stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::size () const [inline]
Examples:
containers/test_vector_export.cpp, and stream/test_stream.cpp.
Definition at line 1118 of file vector.h.
Referenced by main(), stxxl::matrix_operations< ValueType, BlockSideLength >::matrix_col_vector_multiply_and_add_swappable_block(), stxxl::matrix_operations< ValueType, BlockSideLength >::matrix_from_vectors_swappable_block(), stxxl::matrix_operations< ValueType, BlockSideLength >::matrix_row_vector_multiply_and_add_swappable_block(), stxxl::matrix< ValueType, BlockSideLength >::multiply_from_left(), stxxl::matrix< ValueType, BlockSideLength >::operator*(), stxxl::column_vector< ValueType >::operator+(), stxxl::row_vector< ValueType >::operator+(), stxxl::column_vector< ValueType >::operator+=(), stxxl::row_vector< ValueType >::operator+=(), stxxl::column_vector< ValueType >::operator-(), stxxl::row_vector< ValueType >::operator-(), stxxl::column_vector< ValueType >::operator-=(), stxxl::row_vector< ValueType >::operator-=(), short_test(), and test_write().
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> size_type stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::size_from_file_length (stxxl::uint64 file_length) const [inline, private]
Definition at line 788 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> void stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::swap (vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ > & obj) [inline]
Definition at line 843 of file vector.h.
Referenced by std::swap().
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> void stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::write_page (int_type page_no, int_type cache_slot) const [inline, private]
Definition at line 1343 of file vector.h.
Member Data Documentation
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> bids_container_type stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::_bids [private]
Definition at line 774 of file vector.h.
Referenced by stxxl::vector< ValueType >::swap().
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> simple_vector<block_type>* stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::_cache [mutable, private]
Definition at line 782 of file vector.h.
Referenced by stxxl::vector< ValueType >::swap().
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> std::queue<int_type> stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::_free_slots [mutable, private]
Definition at line 781 of file vector.h.
Referenced by stxxl::vector< ValueType >::swap().
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> file* stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::_from [private]
Definition at line 783 of file vector.h.
Referenced by stxxl::vector< ValueType >::swap().
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> std::vector<unsigned char> stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::_page_status [mutable, private]
Definition at line 778 of file vector.h.
Referenced by stxxl::vector< ValueType >::swap().
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> std::vector<int_type> stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::_page_to_slot [mutable, private]
Definition at line 779 of file vector.h.
Referenced by stxxl::vector< ValueType >::swap().
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> size_type stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::_size [private]
Definition at line 773 of file vector.h.
Referenced by stxxl::vector< ValueType >::swap().
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> simple_vector<int_type> stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::_slot_to_page [mutable, private]
Definition at line 780 of file vector.h.
Referenced by stxxl::vector< ValueType >::swap().
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> alloc_strategy_type stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::alloc_strategy [private]
Definition at line 772 of file vector.h.
Referenced by stxxl::vector< ValueType >::swap().
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> block_manager* stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::bm [private]
Definition at line 784 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> config* stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::cfg [private]
Definition at line 785 of file vector.h.
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> bool stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::exported [private]
Definition at line 786 of file vector.h.
Referenced by stxxl::vector< ValueType >::swap(), and stxxl::vector< ValueType >::vector().
template<typename Tp_, unsigned PgSz_ = 4, typename PgTp_ = lru_pager<8>, unsigned BlkSize_ = STXXL_DEFAULT_BLOCK_SIZE(Tp_), typename AllocStr_ = STXXL_DEFAULT_ALLOC_STRATEGY, typename SzTp_ = stxxl::uint64> pager_type stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::pager [mutable, private]
Definition at line 775 of file vector.h.
Referenced by stxxl::vector< ValueType >::swap().
The documentation for this class was generated from the following file:
include/stxxl/bits/containers/vector.h