Stxxl: stxxl::column_vector< ValueType > Class Template Reference
stxxl::column_vector< ValueType > Class Template Reference
external column-vector container for matrix multiplication
#include <matrix.h>
Public Types
typedef vector< ValueType > vector_type
typedef vector_type::size_type size_type
Public Member Functions
column_vector (size_type n=0)
column_vector operator+ (const column_vector &right) const
column_vector operator- (const column_vector &right) const
column_vector operator* (const ValueType scalar) const
column_vector & operator+= (const column_vector &right)
column_vector & operator-= (const column_vector &right)
column_vector & operator*= (const ValueType scalar)
void set_zero ()
Detailed Description
template<typename ValueType>
class stxxl::column_vector< ValueType >
external column-vector container for matrix multiplication
Template Parameters:
ValueType type of contained objects (POD with no references to internal memory)
Definition at line 44 of file matrix.h.
Member Typedef Documentation
template<typename ValueType> typedef vector_type::size_type stxxl::column_vector< ValueType >::size_type
Reimplemented from stxxl::vector< ValueType >.
Definition at line 48 of file matrix.h.
template<typename ValueType> typedef vector<ValueType> stxxl::column_vector< ValueType >::vector_type
Definition at line 47 of file matrix.h.
Constructor & Destructor Documentation
template<typename ValueType> stxxl::column_vector< ValueType >::column_vector (size_type n = 0) [inline]
Parameters:
n number of elements
Definition at line 53 of file matrix.h.
Member Function Documentation
template<typename ValueType> column_vector stxxl::column_vector< ValueType >::operator* (const ValueType scalar) const [inline]
Definition at line 74 of file matrix.h.
template<typename ValueType> column_vector& stxxl::column_vector< ValueType >::operator*= (const ValueType scalar) [inline]
Definition at line 98 of file matrix.h.
template<typename ValueType> column_vector stxxl::column_vector< ValueType >::operator+ (const column_vector< ValueType > & right) const [inline]
Definition at line 56 of file matrix.h.
References stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::size().
template<typename ValueType> column_vector& stxxl::column_vector< ValueType >::operator+= (const column_vector< ValueType > & right) [inline]
Definition at line 82 of file matrix.h.
References stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::size().
template<typename ValueType> column_vector stxxl::column_vector< ValueType >::operator- (const column_vector< ValueType > & right) const [inline]
Definition at line 65 of file matrix.h.
References stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::size().
template<typename ValueType> column_vector& stxxl::column_vector< ValueType >::operator-= (const column_vector< ValueType > & right) [inline]
Definition at line 90 of file matrix.h.
References stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::size().
template<typename ValueType> void stxxl::column_vector< ValueType >::set_zero () [inline]
Definition at line 105 of file matrix.h.
References stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::begin(), and stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::end().
Referenced by stxxl::matrix< ValueType, BlockSideLength >::operator*().
The documentation for this class was generated from the following file:
include/stxxl/bits/containers/matrix.h