Stxxl: stxxl::stable_ksort_local::bid_sequence< BIDType_, AllocStrategy_ > Class Template Reference
stxxl::stable_ksort_local::bid_sequence< BIDType_, AllocStrategy_ > Class Template Reference
#include <stable_ksort.h>
Public Types
typedef BIDType_ bid_type
typedef bid_type & reference
typedef AllocStrategy_ alloc_strategy
typedef simple_vector
< bid_type >::size_type size_type
typedef simple_vector
< bid_type >::iterator iterator
Public Member Functions
bid_sequence ()
bid_sequence (size_type size_)
void init (size_type size_)
reference operator[] (size_type i)
size_type size ()
iterator begin ()
~bid_sequence ()
Protected Attributes
simple_vector< bid_type > * bids
alloc_strategy alloc_strategy_
Detailed Description
template<typename BIDType_, typename AllocStrategy_>
class stxxl::stable_ksort_local::bid_sequence< BIDType_, AllocStrategy_ >
Definition at line 83 of file stable_ksort.h.
Member Typedef Documentation
template<typename BIDType_ , typename AllocStrategy_ > typedef AllocStrategy_ stxxl::stable_ksort_local::bid_sequence< BIDType_, AllocStrategy_ >::alloc_strategy
Definition at line 88 of file stable_ksort.h.
template<typename BIDType_ , typename AllocStrategy_ > typedef BIDType_ stxxl::stable_ksort_local::bid_sequence< BIDType_, AllocStrategy_ >::bid_type
Definition at line 86 of file stable_ksort.h.
template<typename BIDType_ , typename AllocStrategy_ > typedef simple_vector<bid_type>::iterator stxxl::stable_ksort_local::bid_sequence< BIDType_, AllocStrategy_ >::iterator
Definition at line 90 of file stable_ksort.h.
template<typename BIDType_ , typename AllocStrategy_ > typedef bid_type& stxxl::stable_ksort_local::bid_sequence< BIDType_, AllocStrategy_ >::reference
Definition at line 87 of file stable_ksort.h.
template<typename BIDType_ , typename AllocStrategy_ > typedef simple_vector<bid_type>::size_type stxxl::stable_ksort_local::bid_sequence< BIDType_, AllocStrategy_ >::size_type
Definition at line 89 of file stable_ksort.h.
Constructor & Destructor Documentation
template<typename BIDType_ , typename AllocStrategy_ > stxxl::stable_ksort_local::bid_sequence< BIDType_, AllocStrategy_ >::bid_sequence () [inline]
Definition at line 97 of file stable_ksort.h.
template<typename BIDType_ , typename AllocStrategy_ > stxxl::stable_ksort_local::bid_sequence< BIDType_, AllocStrategy_ >::bid_sequence (size_type size_) [inline]
Definition at line 98 of file stable_ksort.h.
template<typename BIDType_ , typename AllocStrategy_ > stxxl::stable_ksort_local::bid_sequence< BIDType_, AllocStrategy_ >::~bid_sequence () [inline]
Definition at line 126 of file stable_ksort.h.
Member Function Documentation
template<typename BIDType_ , typename AllocStrategy_ > iterator stxxl::stable_ksort_local::bid_sequence< BIDType_, AllocStrategy_ >::begin () [inline]
Definition at line 125 of file stable_ksort.h.
template<typename BIDType_ , typename AllocStrategy_ > void stxxl::stable_ksort_local::bid_sequence< BIDType_, AllocStrategy_ >::init (size_type size_) [inline]
Definition at line 104 of file stable_ksort.h.
template<typename BIDType_ , typename AllocStrategy_ > reference stxxl::stable_ksort_local::bid_sequence< BIDType_, AllocStrategy_ >::operator[] (size_type i) [inline]
Definition at line 110 of file stable_ksort.h.
References stxxl::simple_vector< _Tp >::begin(), stxxl::simple_vector< _Tp >::end(), and stxxl::block_manager::new_blocks().
template<typename BIDType_ , typename AllocStrategy_ > size_type stxxl::stable_ksort_local::bid_sequence< BIDType_, AllocStrategy_ >::size () [inline]
Definition at line 124 of file stable_ksort.h.
Member Data Documentation
template<typename BIDType_ , typename AllocStrategy_ > alloc_strategy stxxl::stable_ksort_local::bid_sequence< BIDType_, AllocStrategy_ >::alloc_strategy_ [protected]
Definition at line 94 of file stable_ksort.h.
template<typename BIDType_ , typename AllocStrategy_ > simple_vector<bid_type>* stxxl::stable_ksort_local::bid_sequence< BIDType_, AllocStrategy_ >::bids [protected]
Definition at line 93 of file stable_ksort.h.
The documentation for this class was generated from the following file:
include/stxxl/bits/algo/stable_ksort.h