Stxxl: stxxl::simple_vector< _Tp > Class Template Reference
stxxl::simple_vector< _Tp > Class Template Reference
#include <simple_vector.h>
Public Types
typedef unsigned_type size_type
typedef _Tp value_type
typedef value_type * iterator
typedef const value_type * const_iterator
typedef value_type & reference
typedef const value_type & const_reference
Public Member Functions
simple_vector (size_type sz)
void swap (simple_vector &obj)
~simple_vector ()
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
const_iterator end () const
const_iterator cend () const
size_type size () const
reference operator[] (size_type i)
const_reference operator[] (size_type i) const
Protected Attributes
size_type _size
value_type * _array
Detailed Description
template<class _Tp>
class stxxl::simple_vector< _Tp >
Definition at line 25 of file simple_vector.h.
Member Typedef Documentation
template<class _Tp> typedef const value_type* stxxl::simple_vector< _Tp >::const_iterator
Definition at line 38 of file simple_vector.h.
template<class _Tp> typedef const value_type& stxxl::simple_vector< _Tp >::const_reference
Definition at line 40 of file simple_vector.h.
template<class _Tp> typedef value_type* stxxl::simple_vector< _Tp >::iterator
Definition at line 37 of file simple_vector.h.
template<class _Tp> typedef value_type& stxxl::simple_vector< _Tp >::reference
Definition at line 39 of file simple_vector.h.
template<class _Tp> typedef unsigned_type stxxl::simple_vector< _Tp >::size_type
Definition at line 28 of file simple_vector.h.
template<class _Tp> typedef _Tp stxxl::simple_vector< _Tp >::value_type
Definition at line 29 of file simple_vector.h.
Constructor & Destructor Documentation
template<class _Tp> stxxl::simple_vector< _Tp >::simple_vector (size_type sz) [inline]
Definition at line 42 of file simple_vector.h.
template<class _Tp> stxxl::simple_vector< _Tp >::~simple_vector () [inline]
Definition at line 53 of file simple_vector.h.
Member Function Documentation
template<class _Tp> iterator stxxl::simple_vector< _Tp >::begin () [inline]
Definition at line 58 of file simple_vector.h.
Referenced by stxxl::stable_ksort_local::bid_sequence< BIDType_, AllocStrategy_ >::operator[](), stxxl::normal_stack< Config_ >::pop(), stxxl::normal_stack< Config_ >::push(), and stxxl::stl_in_memory_sort().
template<class _Tp> const_iterator stxxl::simple_vector< _Tp >::begin () const [inline]
Definition at line 62 of file simple_vector.h.
template<class _Tp> const_iterator stxxl::simple_vector< _Tp >::cbegin () const [inline]
Definition at line 66 of file simple_vector.h.
template<class _Tp> const_iterator stxxl::simple_vector< _Tp >::cend () const [inline]
Definition at line 78 of file simple_vector.h.
template<class _Tp> iterator stxxl::simple_vector< _Tp >::end () [inline]
Definition at line 70 of file simple_vector.h.
Referenced by stxxl::stable_ksort_local::bid_sequence< BIDType_, AllocStrategy_ >::operator[]().
template<class _Tp> const_iterator stxxl::simple_vector< _Tp >::end () const [inline]
Definition at line 74 of file simple_vector.h.
template<class _Tp> reference stxxl::simple_vector< _Tp >::operator[] (size_type i) [inline]
Definition at line 86 of file simple_vector.h.
template<class _Tp> const_reference stxxl::simple_vector< _Tp >::operator[] (size_type i) const [inline]
Definition at line 90 of file simple_vector.h.
template<class _Tp> size_type stxxl::simple_vector< _Tp >::size () const [inline]
Definition at line 82 of file simple_vector.h.
template<class _Tp> void stxxl::simple_vector< _Tp >::swap (simple_vector< _Tp > & obj) [inline]
Definition at line 48 of file simple_vector.h.
Referenced by std::swap().
Member Data Documentation
template<class _Tp> value_type* stxxl::simple_vector< _Tp >::_array [protected]
Definition at line 34 of file simple_vector.h.
Referenced by stxxl::simple_vector< block_type >::swap().
template<class _Tp> size_type stxxl::simple_vector< _Tp >::_size [protected]
Definition at line 33 of file simple_vector.h.
Referenced by stxxl::simple_vector< block_type >::swap().
The documentation for this class was generated from the following file:
include/stxxl/bits/common/simple_vector.h