Stxxl: stxxl::priority_queue_local::internal_bounded_stack< Tp_, max_size_ > Class Template Reference
stxxl::priority_queue_local::internal_bounded_stack< Tp_, max_size_ > Class Template Reference
Similar to std::stack, with the following differences:
#include <pq_helpers.h>
Public Member Functions
internal_bounded_stack ()
void push (const value_type &x)
const value_type & top () const
void pop ()
void clear ()
size_type size () const
bool empty () const
Private Types
enum { max_size = max_size_ }
typedef Tp_ value_type
typedef unsigned_type size_type
Private Attributes
size_type size_
value_type array [max_size]
Detailed Description
template<typename Tp_, unsigned_type max_size_>
class stxxl::priority_queue_local::internal_bounded_stack< Tp_, max_size_ >
Similar to std::stack, with the following differences:
Maximum size is fixed at compilation time, so an array can be used.
Can be cleared "at once", without reallocation.
Definition at line 168 of file pq_helpers.h.
Member Typedef Documentation
template<typename Tp_, unsigned_type max_size_> typedef unsigned_type stxxl::priority_queue_local::internal_bounded_stack< Tp_, max_size_ >::size_type [private]
Definition at line 171 of file pq_helpers.h.
template<typename Tp_, unsigned_type max_size_> typedef Tp_ stxxl::priority_queue_local::internal_bounded_stack< Tp_, max_size_ >::value_type [private]
Definition at line 170 of file pq_helpers.h.
Member Enumeration Documentation
template<typename Tp_, unsigned_type max_size_> anonymous enum [private]
Enumerator:
max_size
Definition at line 172 of file pq_helpers.h.
Constructor & Destructor Documentation
template<typename Tp_, unsigned_type max_size_> stxxl::priority_queue_local::internal_bounded_stack< Tp_, max_size_ >::internal_bounded_stack () [inline]
Definition at line 178 of file pq_helpers.h.
Member Function Documentation
template<typename Tp_, unsigned_type max_size_> void stxxl::priority_queue_local::internal_bounded_stack< Tp_, max_size_ >::clear () [inline]
Definition at line 198 of file pq_helpers.h.
Referenced by stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::compact_tree().
template<typename Tp_, unsigned_type max_size_> bool stxxl::priority_queue_local::internal_bounded_stack< Tp_, max_size_ >::empty () const [inline]
Definition at line 208 of file pq_helpers.h.
Referenced by stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::double_k(), stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::insert_segment(), stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::is_space_available(), and stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::multi_merge().
template<typename Tp_, unsigned_type max_size_> void stxxl::priority_queue_local::internal_bounded_stack< Tp_, max_size_ >::pop () [inline]
Definition at line 192 of file pq_helpers.h.
Referenced by stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::insert_segment().
template<typename Tp_, unsigned_type max_size_> void stxxl::priority_queue_local::internal_bounded_stack< Tp_, max_size_ >::push (const value_type & x) [inline]
Definition at line 180 of file pq_helpers.h.
Referenced by stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::compact_tree(), stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::deallocate_segment(), stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::double_k(), stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::init(), and stxxl::priority_queue_local::loser_tree< ValTp_, Cmp_, KNKMAX >::loser_tree().
template<typename Tp_, unsigned_type max_size_> size_type stxxl::priority_queue_local::internal_bounded_stack< Tp_, max_size_ >::size () const [inline]
Definition at line 203 of file pq_helpers.h.
Referenced by stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::compact_tree(), stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::double_k(), and stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::multi_merge().
template<typename Tp_, unsigned_type max_size_> const value_type& stxxl::priority_queue_local::internal_bounded_stack< Tp_, max_size_ >::top () const [inline]
Definition at line 186 of file pq_helpers.h.
Referenced by stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::insert_segment().
Member Data Documentation
template<typename Tp_, unsigned_type max_size_> value_type stxxl::priority_queue_local::internal_bounded_stack< Tp_, max_size_ >::array[max_size] [private]
Definition at line 175 of file pq_helpers.h.
template<typename Tp_, unsigned_type max_size_> size_type stxxl::priority_queue_local::internal_bounded_stack< Tp_, max_size_ >::size_ [private]
Definition at line 174 of file pq_helpers.h.
The documentation for this class was generated from the following file:
include/stxxl/bits/containers/pq_helpers.h