Stxxl: stxxl::malloc_stats Class Reference
stxxl::malloc_stats Class Reference
Access to some useful malloc statistics.
#include <malloc.h>
Public Types
typedef int return_type
Public Member Functions
return_type from_system_nmmap () const
Returns number of bytes allocated from system not including mmapped regions.
return_type free_chunks () const
Returns number of free chunks.
return_type used () const
Number of bytes allocated and in use.
return_type not_used () const
Number of bytes allocated but not in use.
return_type releasable () const
Top-most, releasable (via malloc_trim) space (bytes)
return_type max_allocated () const
Maximum total allocated space (bytes) (always 0 ?)
return_type fastbin_blocks () const
Number of fastbin blocks.
return_type fastbin_free () const
Space available in freed fastbin blocks (bytes)
return_type from_system_mmap () const
Returns number of bytes allocated from system using mmap.
return_type mmap_chunks () const
Number of chunks allocated via mmap()
return_type from_system_total () const
Returns total number of bytes allocated from system including mmapped regions.
Detailed Description
Access to some useful malloc statistics.
malloc is default C++ allocator
Definition at line 34 of file malloc.h.
Member Typedef Documentation
typedef int stxxl::malloc_stats::return_type
Definition at line 39 of file malloc.h.
Member Function Documentation
return_type stxxl::malloc_stats::fastbin_blocks () const [inline]
Number of fastbin blocks.
Definition at line 84 of file malloc.h.
Referenced by stxxl::operator<<().
return_type stxxl::malloc_stats::fastbin_free () const [inline]
Space available in freed fastbin blocks (bytes)
Definition at line 91 of file malloc.h.
Referenced by stxxl::operator<<().
return_type stxxl::malloc_stats::free_chunks () const [inline]
Returns number of free chunks.
Definition at line 49 of file malloc.h.
Referenced by stxxl::operator<<().
return_type stxxl::malloc_stats::from_system_mmap () const [inline]
Returns number of bytes allocated from system using mmap.
Definition at line 98 of file malloc.h.
Referenced by stxxl::operator<<().
return_type stxxl::malloc_stats::from_system_nmmap () const [inline]
Returns number of bytes allocated from system not including mmapped regions.
Definition at line 42 of file malloc.h.
Referenced by stxxl::operator<<().
return_type stxxl::malloc_stats::from_system_total () const [inline]
Returns total number of bytes allocated from system including mmapped regions.
Definition at line 112 of file malloc.h.
Referenced by stxxl::operator<<().
return_type stxxl::malloc_stats::max_allocated () const [inline]
Maximum total allocated space (bytes) (always 0 ?)
Definition at line 77 of file malloc.h.
Referenced by stxxl::operator<<().
return_type stxxl::malloc_stats::mmap_chunks () const [inline]
Number of chunks allocated via mmap()
Definition at line 105 of file malloc.h.
Referenced by stxxl::operator<<().
return_type stxxl::malloc_stats::not_used () const [inline]
Number of bytes allocated but not in use.
Definition at line 63 of file malloc.h.
Referenced by stxxl::operator<<().
return_type stxxl::malloc_stats::releasable () const [inline]
Top-most, releasable (via malloc_trim) space (bytes)
Definition at line 70 of file malloc.h.
Referenced by stxxl::operator<<().
return_type stxxl::malloc_stats::used () const [inline]
Number of bytes allocated and in use.
Definition at line 56 of file malloc.h.
Referenced by stxxl::operator<<().
The documentation for this class was generated from the following file:
include/stxxl/bits/utils/malloc.h