Stxxl: stxxl::BIDArray< BLK_SIZE > Class Template Reference
stxxl::BIDArray< BLK_SIZE > Class Template Reference
#include <bid.h>
Public Types
typedef BID< BLK_SIZE > & reference
typedef BID< BLK_SIZE > * iterator
typedef const BID< BLK_SIZE > * const_iterator
Public Member Functions
BIDArray ()
iterator begin ()
iterator end ()
BIDArray (unsigned_type size)
unsigned_type size () const
reference operator[] (int_type i)
void resize (unsigned_type newsize)
~BIDArray ()
Protected Attributes
unsigned_type _size
BID< BLK_SIZE > * array
Detailed Description
template<unsigned BLK_SIZE>
class stxxl::BIDArray< BLK_SIZE >
Examples:
mng/test_buf_streams.cpp, and mng/test_mng.cpp.
Definition at line 149 of file bid.h.
Member Typedef Documentation
template<unsigned BLK_SIZE> typedef const BID<BLK_SIZE>* stxxl::BIDArray< BLK_SIZE >::const_iterator
Definition at line 158 of file bid.h.
template<unsigned BLK_SIZE> typedef BID<BLK_SIZE>* stxxl::BIDArray< BLK_SIZE >::iterator
Definition at line 157 of file bid.h.
template<unsigned BLK_SIZE> typedef BID<BLK_SIZE>& stxxl::BIDArray< BLK_SIZE >::reference
Definition at line 156 of file bid.h.
Constructor & Destructor Documentation
template<unsigned BLK_SIZE> stxxl::BIDArray< BLK_SIZE >::BIDArray () [inline]
Definition at line 160 of file bid.h.
template<unsigned BLK_SIZE> stxxl::BIDArray< BLK_SIZE >::BIDArray (unsigned_type size) [inline]
Definition at line 173 of file bid.h.
template<unsigned BLK_SIZE> stxxl::BIDArray< BLK_SIZE >::~BIDArray () [inline]
Definition at line 207 of file bid.h.
Member Function Documentation
template<unsigned BLK_SIZE> iterator stxxl::BIDArray< BLK_SIZE >::begin () [inline]
Definition at line 163 of file bid.h.
Referenced by main(), and stxxl::DiskAllocator::new_blocks().
template<unsigned BLK_SIZE> iterator stxxl::BIDArray< BLK_SIZE >::end () [inline]
Definition at line 168 of file bid.h.
Referenced by main(), and stxxl::DiskAllocator::new_blocks().
template<unsigned BLK_SIZE> reference stxxl::BIDArray< BLK_SIZE >::operator[] (int_type i) [inline]
Definition at line 183 of file bid.h.
template<unsigned BLK_SIZE> void stxxl::BIDArray< BLK_SIZE >::resize (unsigned_type newsize) [inline]
Definition at line 188 of file bid.h.
References stxxl::STXXL_MIN(), and STXXL_MSG.
template<unsigned BLK_SIZE> unsigned_type stxxl::BIDArray< BLK_SIZE >::size () const [inline]
Definition at line 178 of file bid.h.
Member Data Documentation
template<unsigned BLK_SIZE> unsigned_type stxxl::BIDArray< BLK_SIZE >::_size [protected]
Definition at line 152 of file bid.h.
template<unsigned BLK_SIZE> BID<BLK_SIZE>* stxxl::BIDArray< BLK_SIZE >::array [protected]
Definition at line 153 of file bid.h.
The documentation for this class was generated from the following file:
include/stxxl/bits/mng/bid.h