Stxxl: stxxl::stream::unique< Input, BinaryPredicate > Class Template Reference
stxxl::stream::unique< Input, BinaryPredicate > Class Template Reference
Equivalent to std::unique algorithms.
#include <unique.h>
Public Types
typedef Input::value_type value_type
Standard stream typedef.
Public Member Functions
unique (Input &input_, BinaryPredicate binary_pred_)
unique & operator++ ()
Standard stream method.
const value_type & operator* () const
Standard stream method.
const value_type * operator-> () const
Standard stream method.
bool empty () const
Standard stream method.
Private Attributes
Input & input
BinaryPredicate binary_pred
Input::value_type current
Detailed Description
template<class Input, class BinaryPredicate = dummy_cmp_unique_>
class stxxl::stream::unique< Input, BinaryPredicate >
Equivalent to std::unique algorithms.
Removes consecutive duplicates from the stream. Uses BinaryPredicate to compare elements of the stream
Definition at line 36 of file unique.h.
Member Typedef Documentation
template<class Input , class BinaryPredicate = dummy_cmp_unique_> typedef Input::value_type stxxl::stream::unique< Input, BinaryPredicate >::value_type
Standard stream typedef.
Definition at line 44 of file unique.h.
Constructor & Destructor Documentation
template<class Input , class BinaryPredicate = dummy_cmp_unique_> stxxl::stream::unique< Input, BinaryPredicate >::unique (Input & input_, BinaryPredicate binary_pred_) [inline]
Definition at line 46 of file unique.h.
Member Function Documentation
template<class Input , class BinaryPredicate = dummy_cmp_unique_> bool stxxl::stream::unique< Input, BinaryPredicate >::empty () const [inline]
Standard stream method.
Definition at line 75 of file unique.h.
References stxxl::stream::unique< Input, BinaryPredicate >::empty().
Referenced by stxxl::stream::unique< Input, BinaryPredicate >::empty(), and stxxl::stream::unique< Input, dummy_cmp_unique_ >::empty().
template<class Input , class BinaryPredicate = dummy_cmp_unique_> const value_type& stxxl::stream::unique< Input, BinaryPredicate >::operator* () const [inline]
Standard stream method.
Definition at line 63 of file unique.h.
template<class Input , class BinaryPredicate = dummy_cmp_unique_> unique& stxxl::stream::unique< Input, BinaryPredicate >::operator++ () [inline]
Standard stream method.
Definition at line 53 of file unique.h.
template<class Input , class BinaryPredicate = dummy_cmp_unique_> const value_type* stxxl::stream::unique< Input, BinaryPredicate >::operator-> () const [inline]
Standard stream method.
Definition at line 69 of file unique.h.
Member Data Documentation
template<class Input , class BinaryPredicate = dummy_cmp_unique_> BinaryPredicate stxxl::stream::unique< Input, BinaryPredicate >::binary_pred [private]
Definition at line 39 of file unique.h.
template<class Input , class BinaryPredicate = dummy_cmp_unique_> Input::value_type stxxl::stream::unique< Input, BinaryPredicate >::current [private]
Definition at line 40 of file unique.h.
template<class Input , class BinaryPredicate = dummy_cmp_unique_> Input& stxxl::stream::unique< Input, BinaryPredicate >::input [private]
Definition at line 38 of file unique.h.
The documentation for this class was generated from the following file:
include/stxxl/bits/stream/unique.h