Stxxl: stxxl::timer Class Reference
stxxl::timer Class Reference
#include <timer.h>
Public Member Functions
timer (bool start_immediately=false)
void start ()
void stop ()
void reset ()
double seconds ()
double mseconds ()
double useconds ()
Private Member Functions
double timestamp ()
Private Attributes
bool running
double accumulated
double last_clock
Detailed Description
Examples:
containers/berkeley_db_benchmark.cpp, containers/leda_sm_pq_benchmark.cpp, containers/leda_sm_stack_benchmark.cpp, containers/pq_benchmark.cpp, containers/stack_benchmark.cpp, containers/test_pqueue.cpp, and containers/tpie_stack_benchmark.cpp.
Definition at line 51 of file timer.h.
Constructor & Destructor Documentation
stxxl::timer::timer (bool start_immediately = false) [inline]
Definition at line 68 of file timer.h.
References start().
Member Function Documentation
double stxxl::timer::mseconds () [inline]
Examples:
containers/berkeley_db_benchmark.cpp, containers/leda_sm_pq_benchmark.cpp, containers/leda_sm_stack_benchmark.cpp, containers/pq_benchmark.cpp, containers/stack_benchmark.cpp, and containers/tpie_stack_benchmark.cpp.
Definition at line 97 of file timer.h.
References accumulated, last_clock, running, and timestamp().
Referenced by benchmark_delete(), benchmark_insert(), C(), main(), NC(), run_bdb_btree(), run_bdb_btree_big(), run_ledasm_insert_all_delete_all(), run_ledasm_intermixed(), run_stack(), run_stxxl_insert_all_delete_all(), run_stxxl_intermixed(), run_stxxl_map(), run_stxxl_map_big(), and run_tpie_btree_big().
void stxxl::timer::reset () [inline]
Examples:
containers/berkeley_db_benchmark.cpp, containers/leda_sm_pq_benchmark.cpp, containers/leda_sm_stack_benchmark.cpp, containers/pq_benchmark.cpp, containers/test_pqueue.cpp, and containers/tpie_stack_benchmark.cpp.
Definition at line 91 of file timer.h.
References accumulated, last_clock, and timestamp().
Referenced by main(), run_bdb_btree(), run_bdb_btree_big(), run_ledasm_insert_all_delete_all(), run_ledasm_intermixed(), run_stack(), run_stxxl_insert_all_delete_all(), run_stxxl_intermixed(), run_stxxl_map(), run_stxxl_map_big(), and run_tpie_btree_big().
double stxxl::timer::seconds () [inline]
Examples:
containers/test_pqueue.cpp.
Definition at line 113 of file timer.h.
References accumulated, last_clock, running, and timestamp().
Referenced by main().
void stxxl::timer::start () [inline]
Examples:
containers/berkeley_db_benchmark.cpp, containers/leda_sm_pq_benchmark.cpp, containers/leda_sm_stack_benchmark.cpp, containers/pq_benchmark.cpp, containers/stack_benchmark.cpp, containers/test_pqueue.cpp, and containers/tpie_stack_benchmark.cpp.
Definition at line 79 of file timer.h.
References last_clock, running, and timestamp().
Referenced by benchmark_delete(), benchmark_insert(), C(), main(), NC(), run_bdb_btree(), run_bdb_btree_big(), run_ledasm_insert_all_delete_all(), run_ledasm_intermixed(), run_stack(), run_stxxl_insert_all_delete_all(), run_stxxl_intermixed(), run_stxxl_map(), run_stxxl_map_big(), run_tpie_btree_big(), and timer().
void stxxl::timer::stop () [inline]
Examples:
containers/berkeley_db_benchmark.cpp, containers/leda_sm_pq_benchmark.cpp, containers/leda_sm_stack_benchmark.cpp, containers/pq_benchmark.cpp, containers/stack_benchmark.cpp, containers/test_pqueue.cpp, and containers/tpie_stack_benchmark.cpp.
Definition at line 85 of file timer.h.
References accumulated, last_clock, running, and timestamp().
Referenced by benchmark_delete(), benchmark_insert(), C(), main(), NC(), run_bdb_btree(), run_bdb_btree_big(), run_ledasm_insert_all_delete_all(), run_ledasm_intermixed(), run_stack(), run_stxxl_insert_all_delete_all(), run_stxxl_intermixed(), run_stxxl_map(), run_stxxl_map_big(), and run_tpie_btree_big().
double stxxl::timer::timestamp () [inline, private]
Definition at line 74 of file timer.h.
Referenced by mseconds(), reset(), seconds(), start(), stop(), and useconds().
double stxxl::timer::useconds () [inline]
Definition at line 105 of file timer.h.
References accumulated, last_clock, running, and timestamp().
Member Data Documentation
double stxxl::timer::accumulated [private]
Definition at line 54 of file timer.h.
Referenced by mseconds(), reset(), seconds(), stop(), and useconds().
double stxxl::timer::last_clock [private]
Definition at line 55 of file timer.h.
Referenced by mseconds(), reset(), seconds(), start(), stop(), and useconds().
bool stxxl::timer::running [private]
Definition at line 53 of file timer.h.
Referenced by mseconds(), seconds(), start(), stop(), and useconds().
The documentation for this class was generated from the following file:
include/stxxl/bits/common/timer.h