Stxxl: algo/copy_and_sort_file.cpp File Reference
algo/copy_and_sort_file.cpp File Reference
#include <limits>
#include <stxxl/io>
#include <stxxl/vector>
#include <stxxl/stream>
Functions
bool operator< (const my_type &a, const my_type &b)
bool operator== (const my_type &a, const my_type &b)
std::ostream & operator<< (std::ostream &o, const my_type &obj)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 85 of file copy_and_sort_file.cpp.
References stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::begin(), block_size, stxxl::file::CREAT, stxxl::file::DIRECT, stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::end(), stxxl::is_sorted(), stxxl::stream::materialize(), memory_to_use, stxxl::file::RDONLY, stxxl::file::RDWR, stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::resize(), stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::size(), stxxl::stream::streamify(), and STXXL_MSG.
bool operator< (const my_type & a, const my_type & b) [inline]
Definition at line 49 of file copy_and_sort_file.cpp.
std::ostream& operator<< (std::ostream & o, const my_type & obj)
Definition at line 78 of file copy_and_sort_file.cpp.
bool operator== (const my_type & a, const my_type & b) [inline]
Definition at line 54 of file copy_and_sort_file.cpp.