Stxxl: I/O primitives layer
I/O primitives layer
Classes
class stxxl::disk_queues
Encapsulates disk queues.
class stxxl::file
Defines interface of file.
class stxxl::stats
Collects various I/O statistics.
class stxxl::stats_data
class stxxl::request
Request with basic properties like file and offset.
class stxxl::request_interface
Functional interface of a request.
class stxxl::request_ptr
Implemented as reference counting smart pointer.
class stxxl::request_queue
class stxxl::request_queue_impl_1q
class stxxl::request_queue_impl_qwqr
class stxxl::request_queue_impl_worker
class stxxl::serving_request
Request which serves an I/O by calling the synchronous routine of the file.
Modules
File implementations
Defines
#define BLOCK_ALIGN 4096
#define STXXL_VERBOSE_request_ptr(msg) STXXL_VERBOSE3("[" << static_cast<void *>(this) << "] request_ptr::" << msg << " ptr=" << static_cast<void *>(ptr))
A smart wrapper for request pointer.
Functions
std::ostream & stxxl::operator<< (std::ostream &o, const stats_data &s)
std::ostream & stxxl::operator<< (std::ostream &o, const stats &s)
std::string stxxl::format_with_SI_IEC_unit_multiplier (uint64 number, const char *unit, int multiplier)
std::string stxxl::add_IEC_binary_multiplier (uint64 number, const char *unit="")
std::string stxxl::add_SI_multiplier (uint64 number, const char *unit="")
std::ostream & stxxl::operator<< (std::ostream &out, const request &req)
template<class request_iterator_ >
void stxxl::wait_all (request_iterator_ reqs_begin, request_iterator_ reqs_end)
Collection of functions to track statuses of a number of requests.
void stxxl::wait_all (request_ptr req_array[], int count)
Suspends calling thread until all given requests are completed.
template<class request_iterator_ >
std::iterator_traits
< request_iterator_ >
::difference_type stxxl::cancel_all (request_iterator_ reqs_begin, request_iterator_ reqs_end)
Cancel requests The specified requests are canceled unless already being processed. However, cancelation cannot be guaranteed. Cancelled requests must still be waited for in order to ensure correct operation.
template<class request_iterator_ >
request_iterator_ stxxl::poll_any (request_iterator_ reqs_begin, request_iterator_ reqs_end)
Polls requests.
bool stxxl::poll_any (request_ptr req_array[], int count, int &index)
Polls requests.
template<class request_iterator_ >
request_iterator_ stxxl::wait_any (request_iterator_ reqs_begin, request_iterator_ reqs_end)
Suspends calling thread until any of requests is completed.
int stxxl::wait_any (request_ptr req_array[], int count)
Suspends calling thread until any of requests is completed.
Detailed Description
Group of classes which enable abstraction from operating system calls and support system-independent interfaces for asynchronous I/O.
Define Documentation
#define BLOCK_ALIGN 4096
Definition at line 33 of file request.h.
#define STXXL_VERBOSE_request_ptr (msg) STXXL_VERBOSE3("[" << static_cast<void *>(this) << "] request_ptr::" << msg << " ptr=" << static_cast<void *>(ptr))
A smart wrapper for request pointer.
Definition at line 31 of file request_ptr.h.
Referenced by stxxl::request_ptr::operator=(), stxxl::request_ptr::request_ptr(), stxxl::request_ptr::sub_ref(), and stxxl::request_ptr::~request_ptr().
Function Documentation
std::string stxxl::add_IEC_binary_multiplier (uint64 number, const char * unit = "") [inline]
Examples:
io/test_io.cpp, and io/test_io_sizes.cpp.
Definition at line 628 of file iostats.h.
References stxxl::format_with_SI_IEC_unit_multiplier().
Referenced by main(), and run_test().
std::string stxxl::add_SI_multiplier (uint64 number, const char * unit = "") [inline]
Examples:
io/test_io.cpp.
Definition at line 633 of file iostats.h.
References stxxl::format_with_SI_IEC_unit_multiplier().
Referenced by main().
template<class request_iterator_ > std::iterator_traits<request_iterator_>::difference_type stxxl::cancel_all (request_iterator_ reqs_begin, request_iterator_ reqs_end)
Cancel requests The specified requests are canceled unless already being processed. However, cancelation cannot be guaranteed. Cancelled requests must still be waited for in order to ensure correct operation.
Parameters:
reqs_begin begin of request sequence
reqs_end end of request sequence
Returns:
number of request canceled
Examples:
io/test_cancel.cpp.
Definition at line 59 of file request_operations.h.
Referenced by main().
std::string stxxl::format_with_SI_IEC_unit_multiplier (uint64 number, const char * unit, int multiplier)
Definition at line 325 of file iostats.cpp.
Referenced by stxxl::add_IEC_binary_multiplier(), and stxxl::add_SI_multiplier().
std::ostream& stxxl::operator<< (std::ostream & out, const request & req) [inline]
Definition at line 138 of file request.h.
References stxxl::request::print().
std::ostream & stxxl::operator<< (std::ostream & o, const stats_data & s)
Examples:
algo/copy_and_sort_file.cpp, algo/sort_file.cpp, algo/test_bad_cmp.cpp, algo/test_ksort.cpp, algo/test_parallel_sort.cpp, algo/test_sort.cpp, containers/berkeley_db_benchmark.cpp, containers/leda_sm_pq_benchmark.cpp, containers/pq_benchmark.cpp, containers/test_pqueue.cpp, and containers/test_sorter.cpp.
Definition at line 349 of file iostats.cpp.
References stxxl::stats_data::get_cached_read_volume(), stxxl::stats_data::get_cached_reads(), stxxl::stats_data::get_cached_writes(), stxxl::stats_data::get_cached_written_volume(), stxxl::stats_data::get_elapsed_time(), stxxl::stats_data::get_io_wait_time(), stxxl::stats_data::get_pio_time(), stxxl::stats_data::get_pread_time(), stxxl::stats_data::get_pwrite_time(), stxxl::stats_data::get_read_time(), stxxl::stats_data::get_read_volume(), stxxl::stats_data::get_reads(), stxxl::stats_data::get_wait_read_time(), stxxl::stats_data::get_wait_write_time(), stxxl::stats_data::get_write_time(), stxxl::stats_data::get_writes(), stxxl::stats_data::get_written_volume(), and hr.
Referenced by stxxl::buf_ostream< BlkTp_, BIDIteratorTp_ >::fill().
std::ostream& stxxl::operator<< (std::ostream & o, const stats & s) [inline]
Definition at line 620 of file iostats.h.
template<class request_iterator_ > request_iterator_ stxxl::poll_any (request_iterator_ reqs_begin, request_iterator_ reqs_end)
Polls requests.
Parameters:
reqs_begin begin of request sequence to poll
reqs_end end of request sequence to poll
index contains index of the first completed request if any
Returns:
true if any of requests is completed, then index contains valid value, otherwise false
Definition at line 77 of file request_operations.h.
Referenced by stxxl::poll_any().
bool stxxl::poll_any (request_ptr req_array[], int count, int & index) [inline]
Polls requests.
Parameters:
req_array array of request_ptr objects
count size of req_array
index contains index of the first completed request if any
Returns:
true if any of requests is completed, then index contains valid value, otherwise false
Definition at line 95 of file request_operations.h.
References stxxl::count(), and stxxl::poll_any().
template<class request_iterator_ > void stxxl::wait_all (request_iterator_ reqs_begin, request_iterator_ reqs_end)
Collection of functions to track statuses of a number of requests.
Suspends calling thread until all given requests are completed
Parameters:
reqs_begin begin of request sequence to wait for
reqs_end end of request sequence to wait for
Examples:
io/test_cancel.cpp, io/test_io.cpp, io/test_io_sizes.cpp, and mng/test_mng.cpp.
Definition at line 36 of file request_operations.h.
Referenced by stxxl::ksort_local::check_ksorted_runs(), stxxl::sort_local::check_sorted_runs(), stxxl::stream::check_sorted_runs(), stxxl::stream::basic_runs_creator< Input_, CompareType_, BlockSize_, AllocStr_ >::compute_result(), stxxl::sort_local::create_runs(), stxxl::ksort_local::create_runs(), stxxl::ksort(), main(), stxxl::normal_stack< Config_ >::pop(), stxxl::grow_shrink_stack< Config_ >::pop(), stxxl::normal_stack< Config_ >::push(), stxxl::vector< ValueType >::read_page(), run(), run_test(), stxxl::stl_in_memory_sort(), stxxl::wait_all(), stxxl::vector< ValueType >::write_page(), and stxxl::grow_shrink_stack< Config_ >::~grow_shrink_stack().
void stxxl::wait_all (request_ptr req_array[], int count) [inline]
Suspends calling thread until all given requests are completed.
Parameters:
req_array array of request_ptr objects
count size of req_array
Definition at line 45 of file request_operations.h.
References stxxl::wait_all().
template<class request_iterator_ > request_iterator_ stxxl::wait_any (request_iterator_ reqs_begin, request_iterator_ reqs_end)
Suspends calling thread until any of requests is completed.
Parameters:
reqs_begin begin of request sequence to wait for
reqs_end end of request sequence to wait for
Returns:
index in req_array pointing to the first completed request
Definition at line 108 of file request_operations.h.
References stxxl::onoff_switch::wait_for_on().
Referenced by stxxl::buffered_writer< block_type >::get_free_block(), stxxl::write_pool< BlockType >::steal(), and stxxl::wait_any().
int stxxl::wait_any (request_ptr req_array[], int count) [inline]
Suspends calling thread until any of requests is completed.
Parameters:
req_array array of request_ptr objects
count size of req_array
Returns:
index in req_array pointing to the first completed request
Definition at line 154 of file request_operations.h.
References stxxl::wait_any().