Stxxl: Block management layer
Block management layer
Classes
class stxxl::blocked_index< modulo >
struct stxxl::TwoToOneDimArrayAdaptorBase< one_dim_array_type, data_type, pos_type >
class stxxl::ArrayOfSequencesIterator< array_type, value_type, modulo >
struct stxxl::element_iterator_traits< BlockType >
struct stxxl::BID< SIZE >
Block identifier class.
class stxxl::config
Access point to disks properties.
class stxxl::DiskAllocator
class stxxl::block_manager
Block manager class.
class stxxl::FileCreator
class stxxl::filler_struct__< bytes >
Namespaces
namespace stxxl::helper
Modules
Allocation functors
Block scheduling sublayer
Defines
#define STXXL_ADAPTOR_ARITHMETICS(pos)
#define BLOCK_ADAPTOR_OPERATORS(two_to_one_dim_array_adaptor_base)
#define STXXL_DEFAULT_BLOCK_SIZE(type) (2 * 1024 * 1024)
Functions
template<typename BlockType >
element_iterator_traits
< BlockType >
::element_iterator stxxl::make_element_iterator (BlockType *blocks, unsigned_type offset)
template<class BIDType , class DiskAssignFunctor , class OutputIterator >
void stxxl::block_manager::new_blocks_int (const unsigned_type nblocks, const DiskAssignFunctor &functor, unsigned_type offset, OutputIterator out)
template<unsigned BLK_SIZE>
void stxxl::block_manager::delete_block (const BID< BLK_SIZE > &bid)
Deallocates a block.
template<class BIDIteratorClass >
void stxxl::block_manager::delete_blocks (const BIDIteratorClass &bidbegin, const BIDIteratorClass &bidend)
Deallocates blocks.
Detailed Description
Group of classes which help controlling external memory space, managing disks, and allocating and deallocating blocks of external storage
Define Documentation
#define BLOCK_ADAPTOR_OPERATORS (two_to_one_dim_array_adaptor_base)
Definition at line 236 of file adaptor.h.
#define STXXL_ADAPTOR_ARITHMETICS (pos)
Definition at line 139 of file adaptor.h.
#define STXXL_DEFAULT_BLOCK_SIZE (type) (2 * 1024 * 1024)
Examples:
algo/test_parallel_sort.cpp.
Definition at line 247 of file mng.h.
Referenced by stxxl::deque< T, VectorType >::clear(), and main().
Function Documentation
template<unsigned BLK_SIZE> void stxxl::block_manager::delete_block (const BID< BLK_SIZE > & bid)
Deallocates a block.
Parameters:
bid block identifier
Examples:
mng/test_pool_pair.cpp, and mng/test_read_write_pool.cpp.
Definition at line 219 of file mng.h.
References FMT_BID, stxxl::file::get_allocator_id(), stxxl::BID< SIZE >::is_managed(), stxxl::BID< SIZE >::offset, stxxl::BID< SIZE >::size, stxxl::BID< SIZE >::storage, and STXXL_VERBOSE_BLOCK_LIFE_CYCLE.
Referenced by stxxl::sort_local::create_runs(), stxxl::ksort_local::create_runs(), stxxl::ksort(), main(), stxxl::sort_local::merge_runs(), stxxl::ksort_local::merge_runs(), and stxxl::sort().
template<class BIDIteratorClass > void stxxl::block_manager::delete_blocks (const BIDIteratorClass & bidbegin, const BIDIteratorClass & bidend)
Deallocates blocks.
Deallocates blocks in the range [ bidbegin, bidend)
Parameters:
bidbegin iterator object of bid_iterator concept
bidend iterator object of bid_iterator concept
Examples:
mng/test_buf_streams.cpp, and mng/test_mng.cpp.
Definition at line 235 of file mng.h.
Referenced by stxxl::stream::basic_runs_creator< Input_, CompareType_, BlockSize_, AllocStr_ >::compute_result(), stxxl::stream::sorted_runs< TriggerEntryType, CompareType_ >::deallocate_blocks(), main(), and stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::sequence_state::~sequence_state().
template<typename BlockType > element_iterator_traits<BlockType>::element_iterator stxxl::make_element_iterator (BlockType * blocks, unsigned_type offset) [inline]
Definition at line 630 of file adaptor.h.
Referenced by stxxl::ksort_local::check_ksorted_runs(), stxxl::sort_local::check_sorted_runs(), stxxl::stream::check_sorted_runs(), stxxl::sort_local::create_runs(), stxxl::stream::basic_runs_creator< stream::use_push< ValueType >, cmp_type, BlockSize_, alloc_strategy_type >::fetch(), stxxl::stream::basic_runs_creator< stream::use_push< ValueType >, cmp_type, BlockSize_, alloc_strategy_type >::fill_with_max_value(), stxxl::stream::runs_creator< use_push< ValueType_ >, CompareType_, BlockSize_, AllocStr_ >::fill_with_max_value(), stxxl::stream::basic_runs_creator< stream::use_push< ValueType >, cmp_type, BlockSize_, alloc_strategy_type >::sort_run(), stxxl::stream::runs_creator< use_push< ValueType_ >, CompareType_, BlockSize_, AllocStr_ >::sort_run(), and stxxl::stl_in_memory_sort().
template<class BIDType , class DiskAssignFunctor , class OutputIterator > void stxxl::block_manager::new_blocks_int (const unsigned_type nblocks, const DiskAssignFunctor & functor, unsigned_type offset, OutputIterator out)
Definition at line 166 of file mng.h.
References FMT_BID, stxxl::file::get_allocator_id(), and STXXL_VERBOSE_BLOCK_LIFE_CYCLE.