Stxxl: containers/leda_sm_stack_benchmark.cpp File Reference
containers/leda_sm_stack_benchmark.cpp File Reference
#include <iostream>
#include <algorithm>
#include <LEDA-SM/ext_stack.h>
#include <LEDA-SM/ext_memory_manager.h>
#include <LEDA-SM/debug.h>
#include <LEDA/random_source.h>
#include <LEDA/stack.h>
#include <LEDA-SM/block.h>
#include <LEDA-SM/name_server.h>
#include <stxxl/types>
#include <stxxl/timer>
Defines
#define DEBUG 0
#define DD 500
#define STXXL_MSG(x)
#define MEM_2_RESERVE (768 * 1024 * 1024)
#define BLOCK_SIZE1 (EXT_BLK_SZ * 4)
#define BLOCK_SIZE2 (DISK_BLOCK_SIZE * 4)
#define DISKS 1
Functions
template<class my_record >
void run_stack (stxxl::int64 volume)
int main (int argc, char *argv[])
Define Documentation
#define BLOCK_SIZE1 (EXT_BLK_SZ * 4)
Definition at line 44 of file leda_sm_stack_benchmark.cpp.
Referenced by main().
#define BLOCK_SIZE2 (DISK_BLOCK_SIZE * 4)
Definition at line 45 of file leda_sm_stack_benchmark.cpp.
Referenced by main().
#define DD 500
Definition at line 32 of file leda_sm_stack_benchmark.cpp.
#define DEBUG 0
Definition at line 31 of file leda_sm_stack_benchmark.cpp.
#define DISKS 1
Examples:
containers/stack_benchmark.cpp, and containers/tpie_stack_benchmark.cpp.
Definition at line 49 of file leda_sm_stack_benchmark.cpp.
#define MEM_2_RESERVE (768 * 1024 * 1024)
Examples:
containers/leda_sm_stack_benchmark.cpp, containers/stack_benchmark.cpp, and containers/tpie_stack_benchmark.cpp.
Definition at line 42 of file leda_sm_stack_benchmark.cpp.
Referenced by main().
#define STXXL_MSG (x)
Value:
{ std::cout << "[STXXL-MSG] " << x << std::endl << std::flush; \
    }
Definition at line 37 of file leda_sm_stack_benchmark.cpp.
Referenced by main(), and run_stack().
Function Documentation
int main (int argc, char * argv[])
Definition at line 126 of file leda_sm_stack_benchmark.cpp.
References BLOCK_SIZE1, BLOCK_SIZE2, MEM_2_RESERVE, and STXXL_MSG.
template<class my_record > void run_stack (stxxl::int64 volume)
Examples:
containers/leda_sm_stack_benchmark.cpp, and containers/tpie_stack_benchmark.cpp.
Definition at line 61 of file leda_sm_stack_benchmark.cpp.
References stxxl::timer::mseconds(), stxxl::timer::reset(), stxxl::timer::start(), stxxl::timer::stop(), and STXXL_MSG.