Stxxl: containers/matrix_benchmark.cpp File Reference
containers/matrix_benchmark.cpp File Reference
#include <iostream>
#include <limits>
#include <Argument_helper.h>
#include <stxxl/vector>
#include <stxxl/stream>
#include <stxxl/bits/containers/matrix.h>
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 25 of file matrix_benchmark.cpp.
References stxxl::matrix_operation_statistic_dataset::block_addition_calls, stxxl::matrix_operation_statistic_dataset::block_additions_saved_through_zero, stxxl::matrix_operation_statistic_dataset::block_multiplication_calls, stxxl::matrix_operation_statistic_dataset::block_multiplications_saved_through_zero, C(), D(), stxxl::stats_data::get_elapsed_time(), stxxl::stats_data::get_pio_time(), stxxl::stats_data::get_pread_time(), stxxl::stats_data::get_pwrite_time(), stxxl::stats_data::get_read_time(), stxxl::stats_data::get_reads(), stxxl::stats_data::get_wait_read_time(), stxxl::stats_data::get_wait_write_time(), stxxl::stats_data::get_write_time(), stxxl::stats_data::get_writes(), stxxl::matrix_operation_statistic_data::set(), and STXXL_MSG.