Stxxl: containers/monotonic_pq.cpp File Reference
containers/monotonic_pq.cpp File Reference
#include <queue>
#include <limits>
#include <stxxl/priority_queue>
#include <stxxl/stats>
#include <stxxl/timer>
Defines
#define STXXL_PARALLEL_PQ_MULTIWAY_MERGE_EXTERNAL 1
#define STXXL_PARALLEL_PQ_MULTIWAY_MERGE_INTERNAL 1
#define STXXL_PARALLEL_PQ_MULTIWAY_MERGE_DELETE_BUFFER 1
#define TINY_PQ 0
#define MANUAL_PQ 0
#define SIDE_PQ 1
#define RECORD_SIZE 16
#define LOAD 0
#define MAGIC 123
Typedefs
typedef stxxl::uint64 my_key_type
Functions
std::ostream & operator<< (std::ostream &o, const my_type &obj)
int main (int argc, char *argv[])
Variables
const stxxl::unsigned_type mega = 1024 * 1024
const stxxl::unsigned_type block_size = 4 * mega
Define Documentation
#define LOAD 0
Definition at line 37 of file monotonic_pq.cpp.
#define MAGIC 123
Examples:
algo/test_parallel_sort.cpp.
Definition at line 41 of file monotonic_pq.cpp.
#define MANUAL_PQ 0
Definition at line 23 of file monotonic_pq.cpp.
#define RECORD_SIZE 16
Definition at line 36 of file monotonic_pq.cpp.
#define SIDE_PQ 1
Definition at line 25 of file monotonic_pq.cpp.
#define STXXL_PARALLEL_PQ_MULTIWAY_MERGE_DELETE_BUFFER 1
Definition at line 20 of file monotonic_pq.cpp.
#define STXXL_PARALLEL_PQ_MULTIWAY_MERGE_EXTERNAL 1
Definition at line 18 of file monotonic_pq.cpp.
#define STXXL_PARALLEL_PQ_MULTIWAY_MERGE_INTERNAL 1
Definition at line 19 of file monotonic_pq.cpp.
#define TINY_PQ 0
Definition at line 22 of file monotonic_pq.cpp.
Typedef Documentation
typedef stxxl::uint64 my_key_type
Definition at line 39 of file monotonic_pq.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 115 of file monotonic_pq.cpp.
References mega, stxxl::timer::reset(), stxxl::timer::seconds(), stxxl::timer::start(), stxxl::timer::stop(), and STXXL_MSG.
std::ostream& operator<< (std::ostream & o, const my_type & obj)
Definition at line 75 of file monotonic_pq.cpp.
Variable Documentation
const stxxl::unsigned_type block_size = 4 * mega
Definition at line 34 of file monotonic_pq.cpp.
const stxxl::unsigned_type mega = 1024 * 1024
Definition at line 31 of file monotonic_pq.cpp.
Referenced by main().