Stxxl: stxxl::priority_queue_local Namespace Reference
stxxl::priority_queue_local Namespace Reference
Internals
Classes
class short_sequence
class ext_merger
External merger, based on the loser tree data structure. !
class internal_priority_queue
Similar to std::priority_queue, with the following differences:
class invert_order
Inverts the order of a comparison functor by swapping its arguments.
class internal_bounded_stack
Similar to std::stack, with the following differences:
class loser_tree
Loser tree from Knuth, "Sorting and Searching", Section 5.4.1 !
struct Parameters_for_priority_queue_not_found_Increase_IntM
struct dummy
struct find_B_m
struct find_B_m< E_, IntM_, MaxS_, 2048, 1, stop >
struct find_B_m< E_, IntM_, MaxS_, B_, m_, true >
struct find_settings
struct Parameters_not_found_Try_to_change_the_Tune_parameter
struct compute_N
struct compute_N< 1, X_, CriticalSize_ >
Functions
template<class InputIterator , class OutputIterator , class Cmp_ >
void merge_iterator (InputIterator &source0, InputIterator &source1, OutputIterator target, unsigned_type length, Cmp_ &cmp)
template<class InputIterator , class OutputIterator , class Cmp_ >
void merge3_iterator (InputIterator &source0, InputIterator &source1, InputIterator &source2, OutputIterator target, unsigned_type length, Cmp_ &cmp)
template<class InputIterator , class OutputIterator , class Cmp_ >
void merge4_iterator (InputIterator &source0, InputIterator &source1, InputIterator &source2, InputIterator &source3, OutputIterator target, unsigned_type length, Cmp_ &cmp)
Detailed Description
Function Documentation
template<class InputIterator , class OutputIterator , class Cmp_ > void stxxl::priority_queue_local::merge3_iterator (InputIterator & source0, InputIterator & source1, InputIterator & source2, OutputIterator target, unsigned_type length, Cmp_ & cmp)
Definition at line 71 of file pq_mergers.h.
References Merge3Case.
Referenced by stxxl::priority_queue_local::loser_tree< ValTp_, Cmp_, KNKMAX >::multi_merge(), stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::multi_merge(), and stxxl::priority_queue< Config_ >::refill_delete_buffer().
template<class InputIterator , class OutputIterator , class Cmp_ > void stxxl::priority_queue_local::merge4_iterator (InputIterator & source0, InputIterator & source1, InputIterator & source2, InputIterator & source3, OutputIterator target, unsigned_type length, Cmp_ & cmp)
Definition at line 139 of file pq_mergers.h.
References Merge4Case, and StartMerge4.
Referenced by stxxl::priority_queue_local::loser_tree< ValTp_, Cmp_, KNKMAX >::multi_merge(), stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::multi_merge(), and stxxl::priority_queue< Config_ >::refill_delete_buffer().
template<class InputIterator , class OutputIterator , class Cmp_ > void stxxl::priority_queue_local::merge_iterator (InputIterator & source0, InputIterator & source1, OutputIterator target, unsigned_type length, Cmp_ & cmp)
Definition at line 39 of file pq_mergers.h.
Referenced by stxxl::priority_queue< Config_ >::empty_insert_heap(), stxxl::priority_queue_local::loser_tree< ValTp_, Cmp_, KNKMAX >::multi_merge(), stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::multi_merge(), and stxxl::priority_queue< Config_ >::refill_delete_buffer().