Stxxl: std Namespace Reference
std Namespace Reference
Functions
std::ostream & operator<< (std::ostream &os, const tuple_type &t)
template<typename run_cursor_type , typename run_cursor_cmp_type >
void swap (stxxl::loser_tree< run_cursor_type, run_cursor_cmp_type > &a, stxxl::loser_tree< run_cursor_type, run_cursor_cmp_type > &b)
template<class Tp_ >
void swap (stxxl::simple_vector< Tp_ > &a, stxxl::simple_vector< Tp_ > &b)
template<typename T , typename VT >
void swap (stxxl::deque< T, VT > &a, stxxl::deque< T, VT > &b)
template<class KeyType , class DataType , class CompareType , unsigned RawNodeSize, unsigned RawLeafSize, class PDAllocStrategy >
void swap (stxxl::map< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy > &a, stxxl::map< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy > &b)
template<unsigned npages_>
void swap (stxxl::lru_pager< npages_ > &a, stxxl::lru_pager< npages_ > &b)
template<class BlockType_ , class Cmp_ , unsigned Arity_, class AllocStr_ >
void swap (stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ > &a, stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ > &b)
template<class ValTp_ , class Cmp_ , unsigned KNKMAX>
void swap (stxxl::priority_queue_local::loser_tree< ValTp_, Cmp_, KNKMAX > &a, stxxl::priority_queue_local::loser_tree< ValTp_, Cmp_, KNKMAX > &b)
template<class Config_ >
void swap (stxxl::priority_queue< Config_ > &a, stxxl::priority_queue< Config_ > &b)
template<class Config_ >
void swap (stxxl::normal_stack< Config_ > &a, stxxl::normal_stack< Config_ > &b)
template<class Config_ >
void swap (stxxl::grow_shrink_stack< Config_ > &a, stxxl::grow_shrink_stack< Config_ > &b)
template<class Config_ >
void swap (stxxl::grow_shrink_stack2< Config_ > &a, stxxl::grow_shrink_stack2< Config_ > &b)
template<stxxl::unsigned_type CritSize, class ExternalStack , class InternalStack >
void swap (stxxl::migrating_stack< CritSize, ExternalStack, InternalStack > &a, stxxl::migrating_stack< CritSize, ExternalStack, InternalStack > &b)
template<typename Tp_ , unsigned PgSz_, typename PgTp_ , unsigned BlkSize_, typename AllocStr_ , typename SzTp_ >
void swap (stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ > &a, stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ > &b)
template<class KeyType , class DataType , class CompareType , unsigned LogNodeSize, unsigned LogLeafSize, class PDAllocStrategy >
void swap (stxxl::btree::btree< KeyType, DataType, CompareType, LogNodeSize, LogLeafSize, PDAllocStrategy > &a, stxxl::btree::btree< KeyType, DataType, CompareType, LogNodeSize, LogLeafSize, PDAllocStrategy > &b)
template<class BTreeType >
void swap (stxxl::btree::iterator_map< BTreeType > &a, stxxl::btree::iterator_map< BTreeType > &b)
template<class NodeType , class BTreeType >
void swap (stxxl::btree::node_cache< NodeType, BTreeType > &a, stxxl::btree::node_cache< NodeType, BTreeType > &b)
template<class BlockType >
void swap (stxxl::prefetch_pool< BlockType > &a, stxxl::prefetch_pool< BlockType > &b)
template<class BlockType >
void swap (stxxl::read_write_pool< BlockType > &a, stxxl::read_write_pool< BlockType > &b)
template<class BlockType >
void swap (stxxl::write_pool< BlockType > &a, stxxl::write_pool< BlockType > &b)
Function Documentation
std::ostream& std::operator<< (std::ostream & os, const tuple_type & t)
Examples:
stream/test_stream.cpp.
Definition at line 38 of file test_stream.cpp.
References stxxl::tuple< T1, T2, T3, T4, T5, T6 >::first, and stxxl::tuple< T1, T2, T3, T4, T5, T6 >::second.
template<class Tp_ > void std::swap (stxxl::simple_vector< Tp_ > & a, stxxl::simple_vector< Tp_ > & b)
Definition at line 100 of file simple_vector.h.
References stxxl::simple_vector< _Tp >::swap().
template<unsigned npages_> void std::swap (stxxl::lru_pager< npages_ > & a, stxxl::lru_pager< npages_ > & b)
Definition at line 115 of file pager.h.
References stxxl::lru_pager< npages_ >::swap().
template<class BlockType_ , class Cmp_ , unsigned Arity_, class AllocStr_ > void std::swap (stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ > & a, stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ > & b)
Definition at line 125 of file priority_queue.h.
template<class ValTp_ , class Cmp_ , unsigned KNKMAX> void std::swap (stxxl::priority_queue_local::loser_tree< ValTp_, Cmp_, KNKMAX > & a, stxxl::priority_queue_local::loser_tree< ValTp_, Cmp_, KNKMAX > & b)
Definition at line 131 of file priority_queue.h.
References stxxl::priority_queue_local::loser_tree< ValTp_, Cmp_, KNKMAX >::swap().
template<class BTreeType > void std::swap (stxxl::btree::iterator_map< BTreeType > & a, stxxl::btree::iterator_map< BTreeType > & b)
Definition at line 159 of file iterator_map.h.
References stxxl::btree::iterator_map< BTreeType >::swap().
template<class BlockType > void std::swap (stxxl::read_write_pool< BlockType > & a, stxxl::read_write_pool< BlockType > & b)
Definition at line 165 of file read_write_pool.h.
References stxxl::read_write_pool< BlockType >::swap().
template<typename run_cursor_type , typename run_cursor_cmp_type > void std::swap (stxxl::loser_tree< run_cursor_type, run_cursor_cmp_type > & a, stxxl::loser_tree< run_cursor_type, run_cursor_cmp_type > & b)
Examples:
containers/berkeley_db_benchmark.cpp, containers/test_map_random.cpp, containers/test_migr_stack.cpp, containers/test_pqueue.cpp, containers/test_stack.cpp, and containers/test_vector.cpp.
Definition at line 251 of file losertree.h.
References stxxl::loser_tree< run_cursor_type, run_cursor_cmp_type >::swap().
Referenced by stxxl::btree::btree< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::bulk_construction(), stxxl::stream::basic_runs_creator< Input_, CompareType_, BlockSize_, AllocStr_ >::compute_result(), stxxl::sort_local::create_runs(), stxxl::ksort_local::create_runs(), stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::insert_segment(), stxxl::ksort(), stxxl::low_level_matrix_multiply_and_add< ValueType, BlockSideLength >::low_level_matrix_multiply_and_add(), main(), stxxl::priority_queue< Config_ >::make_space_available(), stxxl::stream::basic_runs_merger< RunsType_, CompareType_, AllocStr_ >::merge_recursively(), stxxl::loser_tree< run_cursor_type, run_cursor_cmp_type >::multi_merge_k(), stxxl::btree::node_cache< leaf_type, SelfType >::node_cache(), stxxl::vector< ValueType >::operator=(), stxxl::normal_stack< Config_ >::pop(), stxxl::grow_shrink_stack< Config_ >::pop(), stxxl::normal_stack< Config_ >::push(), stxxl::grow_shrink_stack< Config_ >::push(), stxxl::stream::runs_creator< use_push< ValueType_ >, CompareType_, BlockSize_, AllocStr_ >::push(), run_bdb_btree(), run_bdb_btree_big(), run_stxxl_map(), run_stxxl_map_big(), stxxl::block_scheduler_algorithm_offline_lru_prefetching< SwappableBlockType >::schedule_read(), simple_test(), stxxl::sort(), stxxl::sort2(), stxxl::sort3(), stxxl::sort4(), stxxl::sort5(), stxxl::stable_ksort(), stxxl::simple_vector< block_type >::swap(), stxxl::read_write_pool< BlockType >::swap(), stxxl::write_pool< BlockType >::swap(), stxxl::prefetch_pool< BlockType >::swap(), stxxl::normal_stack< Config_ >::swap(), stxxl::loser_tree< run_cursor_type, run_cursor_cmp_type >::swap(), stxxl::stream::sorted_runs< TriggerEntryType, CompareType_ >::swap(), stxxl::btree::iterator_map< SelfType >::swap(), stxxl::queue< ValTp, BlkSz, AllocStr, SzTp >::swap(), stxxl::deque2< ValueType, BlockSize, AllocStrategy, SizeType >::swap(), stxxl::priority_queue_local::loser_tree< value_type, comparator_type, IntKMAX >::swap(), stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::sequence_state::swap(), stxxl::map< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::swap(), stxxl::grow_shrink_stack< Config_ >::swap(), stxxl::grow_shrink_stack2< Config_ >::swap(), stxxl::btree::node_cache< leaf_type, SelfType >::swap(), stxxl::deque< T, VectorType >::swap(), stxxl::migrating_stack< CritSize, ExternalStack, InternalStack >::swap(), stxxl::vector< ValueType >::swap(), stxxl::btree::btree< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::swap(), stxxl::swap_1D_arrays(), stxxl::swappable_block_matrix< ValueType, BlockSideLength >::transpose(), and stxxl::matrix< ValueType, BlockSideLength >::transpose().
template<class BlockType > void std::swap (stxxl::write_pool< BlockType > & a, stxxl::write_pool< BlockType > & b)
Definition at line 284 of file write_pool.h.
References stxxl::write_pool< BlockType >::swap().
template<class BlockType > void std::swap (stxxl::prefetch_pool< BlockType > & a, stxxl::prefetch_pool< BlockType > & b)
Definition at line 292 of file prefetch_pool.h.
References stxxl::prefetch_pool< BlockType >::swap().
template<class KeyType , class DataType , class CompareType , unsigned RawNodeSize, unsigned RawLeafSize, class PDAllocStrategy > void std::swap (stxxl::map< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy > & a, stxxl::map< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy > & b)
Definition at line 456 of file map.h.
References stxxl::map< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::swap().
template<class NodeType , class BTreeType > void std::swap (stxxl::btree::node_cache< NodeType, BTreeType > & a, stxxl::btree::node_cache< NodeType, BTreeType > & b)
Definition at line 635 of file node_cache.h.
References stxxl::btree::node_cache< NodeType, BTreeType >::swap().
template<typename T , typename VT > void std::swap (stxxl::deque< T, VT > & a, stxxl::deque< T, VT > & b)
Definition at line 662 of file deque.h.
References stxxl::deque< T, VectorType >::swap().
template<class Config_ > void std::swap (stxxl::normal_stack< Config_ > & a, stxxl::normal_stack< Config_ > & b)
Definition at line 866 of file stack.h.
References stxxl::normal_stack< Config_ >::swap().
template<class Config_ > void std::swap (stxxl::grow_shrink_stack< Config_ > & a, stxxl::grow_shrink_stack< Config_ > & b)
Definition at line 873 of file stack.h.
References stxxl::grow_shrink_stack< Config_ >::swap().
template<class Config_ > void std::swap (stxxl::grow_shrink_stack2< Config_ > & a, stxxl::grow_shrink_stack2< Config_ > & b)
Definition at line 880 of file stack.h.
References stxxl::grow_shrink_stack2< Config_ >::swap().
template<stxxl::unsigned_type CritSize, class ExternalStack , class InternalStack > void std::swap (stxxl::migrating_stack< CritSize, ExternalStack, InternalStack > & a, stxxl::migrating_stack< CritSize, ExternalStack, InternalStack > & b)
Definition at line 887 of file stack.h.
References stxxl::migrating_stack< CritSize, ExternalStack, InternalStack >::swap().
template<class Config_ > void std::swap (stxxl::priority_queue< Config_ > & a, stxxl::priority_queue< Config_ > & b)
Definition at line 1063 of file priority_queue.h.
template<class KeyType , class DataType , class CompareType , unsigned LogNodeSize, unsigned LogLeafSize, class PDAllocStrategy > void std::swap (stxxl::btree::btree< KeyType, DataType, CompareType, LogNodeSize, LogLeafSize, PDAllocStrategy > & a, stxxl::btree::btree< KeyType, DataType, CompareType, LogNodeSize, LogLeafSize, PDAllocStrategy > & b)
Definition at line 1155 of file btree.h.
References stxxl::btree::btree< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::swap().
template<typename Tp_ , unsigned PgSz_, typename PgTp_ , unsigned BlkSize_, typename AllocStr_ , typename SzTp_ > void std::swap (stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ > & a, stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ > & b)
Definition at line 1809 of file vector.h.
References stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::swap().