Stxxl: stxxl::sort_local Namespace Reference
stxxl::sort_local Namespace Reference
Algorithms
Classes
struct read_next_after_write_completed
Functions
template<typename block_type , typename run_type , typename input_bid_iterator , typename value_cmp >
void create_runs (input_bid_iterator it, run_type **runs, int_type nruns, int_type _m, value_cmp cmp)
template<typename block_type , typename run_type , typename value_cmp >
bool check_sorted_runs (run_type **runs, unsigned_type nruns, unsigned_type m, value_cmp cmp)
template<typename block_type , typename run_type , typename value_cmp >
void merge_runs (run_type **in_runs, int_type nruns, run_type *out_run, unsigned_type _m, value_cmp cmp)
template<typename block_type , typename alloc_strategy , typename input_bid_iterator , typename value_cmp >
simple_vector
< sort_helper::trigger_entry
< block_type > > * sort_blocks (input_bid_iterator input_bids, unsigned_type _n, unsigned_type _m, value_cmp cmp)
Detailed Description
Function Documentation
template<typename block_type , typename run_type , typename value_cmp > bool stxxl::sort_local::check_sorted_runs (run_type ** runs, unsigned_type nruns, unsigned_type m, value_cmp cmp)
Examples:
stream/test_sorted_runs.cpp.
Definition at line 208 of file sort.h.
References stxxl::is_sorted(), stxxl::make_element_iterator(), stxxl::STXXL_MIN(), STXXL_MSG, and stxxl::wait_all().
Referenced by stxxl::stream::basic_runs_merger< sorted_runs_type, CompareType_, AllocStr_ >::initialize(), and main().
template<typename block_type , typename run_type , typename input_bid_iterator , typename value_cmp > void stxxl::sort_local::create_runs (input_bid_iterator it, run_type ** runs, int_type nruns, int_type _m, value_cmp cmp)
Definition at line 70 of file sort.h.
References stxxl::sort_local::read_next_after_write_completed< block_type, bid_type >::bid, stxxl::sort_local::read_next_after_write_completed< block_type, bid_type >::block, stxxl::block_manager::delete_block(), stxxl::make_element_iterator(), stxxl::sort_local::read_next_after_write_completed< block_type, bid_type >::req, run(), run_size, stxxl::sort(), std::swap(), and stxxl::wait_all().
template<typename block_type , typename run_type , typename value_cmp > void stxxl::sort_local::merge_runs (run_type ** in_runs, int_type nruns, run_type * out_run, unsigned_type _m, value_cmp cmp)
Definition at line 302 of file sort.h.
References stxxl::compute_prefetch_schedule(), stxxl::sort_helper::count_elements_less_equal(), stxxl::block_manager::delete_block(), stxxl::is_sorted(), stxxl::loser_tree< run_cursor_type, run_cursor_cmp_type >::multi_merge(), stxxl::sort_helper::refill_or_remove_empty_sequences(), stxxl::STXXL_MAX(), stxxl::STXXL_MIN(), and STXXL_THROW_UNREACHABLE.
template<typename block_type , typename alloc_strategy , typename input_bid_iterator , typename value_cmp > simple_vector<sort_helper::trigger_entry<block_type> >* stxxl::sort_local::sort_blocks (input_bid_iterator input_bids, unsigned_type _n, unsigned_type _m, value_cmp cmp)
Definition at line 508 of file sort.h.
References stxxl::ksort_local::create_runs(), stxxl::div_ceil(), stxxl::make_bid_iterator(), stxxl::block_manager::new_block(), stxxl::block_manager::new_blocks(), stxxl::optimal_merge_factor(), stxxl::STXXL_MIN(), and stxxl::timestamp().
Referenced by stxxl::sort().