Stxxl: stxxl::async_schedule_local Namespace Reference
stxxl::async_schedule_local Namespace Reference
Typedefs
typedef std::pair< int_type,
int_type > write_time_pair
Functions
static int_type get_disk (int_type i, const int_type *disks, int_type D)
int_type simulate_async_write (const int_type *disks, const int_type L, const int_type m_init, const int_type D, std::pair< int_type, int_type > *o_time)
Typedef Documentation
typedef std::pair<int_type, int_type> stxxl::async_schedule_local::write_time_pair
Definition at line 50 of file async_schedule.cpp.
Function Documentation
static int_type stxxl::async_schedule_local::get_disk (int_type i, const int_type * disks, int_type D) [inline, static]
Definition at line 60 of file async_schedule.cpp.
References D().
Referenced by simulate_async_write().
int_type stxxl::async_schedule_local::simulate_async_write (const int_type * disks, const int_type L, const int_type m_init, const int_type D, std::pair< int_type, int_type > * o_time)
Definition at line 69 of file async_schedule.cpp.
References D(), and get_disk().
Referenced by stxxl::compute_prefetch_schedule().