Stxxl: containers/pq_benchmark.cpp File Reference
containers/pq_benchmark.cpp File Reference
#include <limits>
#include <stxxl/priority_queue>
#include <stxxl/stats>
#include <stxxl/timer>
Defines
#define TOTAL_PQ_MEM_SIZE (768 * 1024 * 1024)
#define PQ_MEM_SIZE (512 * 1024 * 1024)
#define PREFETCH_POOL_SIZE ((TOTAL_PQ_MEM_SIZE - PQ_MEM_SIZE) / 2)
#define WRITE_POOL_SIZE (PREFETCH_POOL_SIZE)
#define MAX_ELEMENTS (2000 * 1024 * 1024)
#define BLOCK_SIZE block_type::raw_size
Typedefs
typedef
stxxl::PRIORITY_QUEUE_GENERATOR
< my_record, comp_type,(512 *1024 *1024),(2000 *1024 *1024)/(1024/8)>
::resul pq_type)
typedef pq_type::block_type block_type
Functions
std::ostream & operator<< (std::ostream &o, const my_record &obj)
bool operator== (const my_record &a, const my_record &b)
bool operator!= (const my_record &a, const my_record &b)
bool operator< (const my_record &a, const my_record &b)
bool operator> (const my_record &a, const my_record &b)
int myrand ()
void run_stxxl_insert_all_delete_all (stxxl::uint64 ops)
void run_stxxl_intermixed (stxxl::uint64 ops)
int main (int argc, char *argv[])
Variables
unsigned ran32State = 0xdeadbeef
Define Documentation
#define BLOCK_SIZE block_type::raw_size
Definition at line 91 of file pq_benchmark.cpp.
Referenced by main().
#define MAX_ELEMENTS (2000 * 1024 * 1024)
Definition at line 35 of file pq_benchmark.cpp.
#define PQ_MEM_SIZE (512 * 1024 * 1024)
Definition at line 29 of file pq_benchmark.cpp.
#define PREFETCH_POOL_SIZE ((TOTAL_PQ_MEM_SIZE - PQ_MEM_SIZE) / 2)
Examples:
containers/pq_benchmark.cpp.
Definition at line 31 of file pq_benchmark.cpp.
Referenced by run_stxxl_insert_all_delete_all(), and run_stxxl_intermixed().
#define TOTAL_PQ_MEM_SIZE (768 * 1024 * 1024)
Definition at line 27 of file pq_benchmark.cpp.
#define WRITE_POOL_SIZE (PREFETCH_POOL_SIZE)
Examples:
containers/pq_benchmark.cpp.
Definition at line 32 of file pq_benchmark.cpp.
Referenced by run_stxxl_insert_all_delete_all(), and run_stxxl_intermixed().
Typedef Documentation
typedef pq_type::block_type block_type
Definition at line 89 of file pq_benchmark.cpp.
typedef stxxl::PRIORITY_QUEUE_GENERATOR<my_record, comp_type, (512 * 1024 * 1024) , (2000 * 1024 * 1024) / (1024 / 8)>::resul pq_type)
Examples:
containers/pq_benchmark.cpp, and containers/test_pqueue.cpp.
Definition at line 87 of file pq_benchmark.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 233 of file pq_benchmark.cpp.
References stxxl::atoint64(), BLOCK_SIZE, run_stxxl_insert_all_delete_all(), run_stxxl_intermixed(), and STXXL_MSG.
int myrand () [inline]
Definition at line 96 of file pq_benchmark.cpp.
bool operator!= (const my_record & a, const my_record & b)
Definition at line 57 of file pq_benchmark.cpp.
bool operator< (const my_record & a, const my_record & b)
Definition at line 62 of file pq_benchmark.cpp.
std::ostream& operator<< (std::ostream & o, const my_record & obj)
Definition at line 46 of file pq_benchmark.cpp.
bool operator== (const my_record & a, const my_record & b)
Definition at line 52 of file pq_benchmark.cpp.
bool operator> (const my_record & a, const my_record & b)
Definition at line 67 of file pq_benchmark.cpp.
void run_stxxl_insert_all_delete_all (stxxl::uint64 ops)
Examples:
containers/pq_benchmark.cpp.
Definition at line 109 of file pq_benchmark.cpp.
References stxxl::timer::mseconds(), myrand(), PREFETCH_POOL_SIZE, stxxl::timer::reset(), stxxl::timer::start(), stxxl::timer::stop(), STXXL_MSG, and WRITE_POOL_SIZE.
Referenced by main().
void run_stxxl_intermixed (stxxl::uint64 ops)
Examples:
containers/pq_benchmark.cpp.
Definition at line 169 of file pq_benchmark.cpp.
References stxxl::timer::mseconds(), myrand(), PREFETCH_POOL_SIZE, stxxl::timer::reset(), stxxl::timer::start(), stxxl::timer::stop(), STXXL_MSG, and WRITE_POOL_SIZE.
Referenced by main().
Variable Documentation
unsigned ran32State = 0xdeadbeef
Definition at line 95 of file pq_benchmark.cpp.