Stxxl: utils/pq_param.cpp File Reference
utils/pq_param.cpp File Reference
#include <iostream>
#include <cmath>
#include <stxxl/types>
Typedefs
typedef stxxl::int64 int64
Functions
int64 D (int64 m, int64 k, int64 MaxS, int64 E, int64 B)
int main ()
Typedef Documentation
typedef stxxl::int64 int64
Definition at line 17 of file pq_param.cpp.
Function Documentation
int64 D (int64 m, int64 k, int64 MaxS, int64 E, int64 B)
Definition at line 19 of file pq_param.cpp.
Referenced by stxxl::deque2< ValueType, BlockSize, AllocStrategy, SizeType >::deque2(), stxxl::async_schedule_local::get_disk(), main(), stxxl::queue< ValTp, BlkSz, AllocStr, SzTp >::queue(), and stxxl::async_schedule_local::simulate_async_write().
int main ()
Definition at line 27 of file pq_param.cpp.
References D().