Stxxl: containers/stack_benchmark.cpp File Reference
containers/stack_benchmark.cpp File Reference
#include <stxxl/stack>
#include <stxxl/stats>
#include <stxxl/timer>
Defines
#define MEM_2_RESERVE (768 * 1024 * 1024)
#define BLOCK_SIZE (2 * 1024 * 1024)
#define DISKS 4
Functions
template<unsigned RECORD_SIZE>
std::ostream & operator<< (std::ostream &o, const my_record_< RECORD_SIZE > &)
template<typename stack_type >
void benchmark_insert (stack_type &Stack, stxxl::int64 volume)
template<typename stack_type >
void benchmark_delete (stack_type &Stack, stxxl::int64 volume)
template<class my_record >
void run_stxxl_growshrink2_stack (stxxl::int64 volume)
template<class my_record >
void run_stxxl_normal_stack (stxxl::int64 volume)
template<class my_record >
void run_stl_stack (stxxl::int64 volume)
int main (int argc, char *argv[])
Define Documentation
#define BLOCK_SIZE (2 * 1024 * 1024)
Definition at line 29 of file stack_benchmark.cpp.
Referenced by main(), run_stxxl_growshrink2_stack(), and run_stxxl_normal_stack().
#define DISKS 4
Definition at line 33 of file stack_benchmark.cpp.
Referenced by run_stxxl_growshrink2_stack(), and run_stxxl_normal_stack().
#define MEM_2_RESERVE (768 * 1024 * 1024)
Definition at line 26 of file stack_benchmark.cpp.
Referenced by main().
Function Documentation
template<typename stack_type > void benchmark_delete (stack_type & Stack, stxxl::int64 volume)
Examples:
containers/stack_benchmark.cpp.
Definition at line 97 of file stack_benchmark.cpp.
References stxxl::timer::mseconds(), stxxl::timer::start(), stxxl::timer::stop(), and STXXL_MSG.
Referenced by run_stl_stack(), run_stxxl_growshrink2_stack(), and run_stxxl_normal_stack().
template<typename stack_type > void benchmark_insert (stack_type & Stack, stxxl::int64 volume)
Examples:
containers/stack_benchmark.cpp.
Definition at line 55 of file stack_benchmark.cpp.
References stxxl::timer::mseconds(), stxxl::timer::start(), stxxl::timer::stop(), and STXXL_MSG.
Referenced by run_stl_stack(), run_stxxl_growshrink2_stack(), and run_stxxl_normal_stack().
int main (int argc, char * argv[])
Definition at line 175 of file stack_benchmark.cpp.
References stxxl::atoint64(), BLOCK_SIZE, MEM_2_RESERVE, and STXXL_MSG.
template<unsigned RECORD_SIZE> std::ostream& operator<< (std::ostream & o, const my_record_< RECORD_SIZE > &) [inline]
Definition at line 47 of file stack_benchmark.cpp.
template<class my_record > void run_stl_stack (stxxl::int64 volume)
Examples:
containers/stack_benchmark.cpp.
Definition at line 164 of file stack_benchmark.cpp.
References benchmark_delete(), and benchmark_insert().
template<class my_record > void run_stxxl_growshrink2_stack (stxxl::int64 volume)
Examples:
containers/stack_benchmark.cpp.
Definition at line 133 of file stack_benchmark.cpp.
References benchmark_delete(), benchmark_insert(), BLOCK_SIZE, DISKS, stxxl::external, and stxxl::grow_shrink2.
template<class my_record > void run_stxxl_normal_stack (stxxl::int64 volume)
Examples:
containers/stack_benchmark.cpp.
Definition at line 151 of file stack_benchmark.cpp.
References benchmark_delete(), benchmark_insert(), BLOCK_SIZE, DISKS, stxxl::external, and stxxl::normal.