Stxxl: stxxl::RC Struct Reference
stxxl::RC Struct Reference
Allocation functors
randomized cycling disk allocation scheme functor
#include <block_alloc.h>
Public Member Functions
RC (int b, int e)
RC ()
int operator() (int i) const
Static Public Member Functions
static const char * name ()
Private Member Functions
void init ()
Private Attributes
std::vector< int > perm
Detailed Description
randomized cycling disk allocation scheme functor
Remarks:
model of allocation_strategy concept
Examples:
stream/test_stream.cpp.
Definition at line 129 of file block_alloc.h.
Constructor & Destructor Documentation
stxxl::RC::RC (int b, int e) [inline]
Definition at line 144 of file block_alloc.h.
References init().
stxxl::RC::RC () [inline]
Definition at line 149 of file block_alloc.h.
References init().
Member Function Documentation
void stxxl::RC::init () [inline, private]
Definition at line 134 of file block_alloc.h.
References stxxl::random_shuffle().
static const char* stxxl::RC::name () [inline, static]
Reimplemented from stxxl::striping.
Reimplemented in stxxl::RC_flash, and stxxl::RC_disk.
Definition at line 159 of file block_alloc.h.
int stxxl::RC::operator() (int i) const [inline]
Reimplemented from stxxl::striping.
Definition at line 154 of file block_alloc.h.
Member Data Documentation
std::vector<int> stxxl::RC::perm [private]
Definition at line 132 of file block_alloc.h.
The documentation for this struct was generated from the following file:
include/stxxl/bits/mng/block_alloc.h