Stxxl: stxxl::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, 0, Granularity > Struct Template Reference
stxxl::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, 0, Granularity > Struct Template Reference
#include <matrix_arithmetic.h>
Public Types
typedef swappable_block_matrix
< ValueType, BlockSideLength > swappable_block_matrix_type
typedef
swappable_block_matrix_type::size_type size_type
Public Member Functions
matrix_to_quadtree_block_grained (const swappable_block_matrix_type &matrix)
matrix_to_quadtree_block_grained (const swappable_block_matrix_type &matrix, const size_type height, const size_type width, const size_type from_row, const size_type from_col)
swappable_block_matrix_type operator() (const size_type &row, const size_type &col)
const size_type get_height ()
const size_type get_width ()
Public Attributes
swappable_block_matrix_type m
Detailed Description
template<typename ValueType, unsigned BlockSideLength, unsigned Granularity>
struct stxxl::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, 0, Granularity >
Definition at line 969 of file matrix_arithmetic.h.
Member Typedef Documentation
template<typename ValueType , unsigned BlockSideLength, unsigned Granularity> typedef swappable_block_matrix_type::size_type stxxl::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, 0, Granularity >::size_type
Definition at line 972 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Granularity> typedef swappable_block_matrix<ValueType, BlockSideLength> stxxl::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, 0, Granularity >::swappable_block_matrix_type
Definition at line 971 of file matrix_arithmetic.h.
Constructor & Destructor Documentation
template<typename ValueType , unsigned BlockSideLength, unsigned Granularity> stxxl::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, 0, Granularity >::matrix_to_quadtree_block_grained (const swappable_block_matrix_type & matrix) [inline]
Definition at line 976 of file matrix_arithmetic.h.
References stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_height(), and stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_width().
template<typename ValueType , unsigned BlockSideLength, unsigned Granularity> stxxl::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, 0, Granularity >::matrix_to_quadtree_block_grained (const swappable_block_matrix_type & matrix, const size_type height, const size_type width, const size_type from_row, const size_type from_col) [inline]
Definition at line 980 of file matrix_arithmetic.h.
References stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_height(), and stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_width().
Member Function Documentation
template<typename ValueType , unsigned BlockSideLength, unsigned Granularity> const size_type stxxl::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, 0, Granularity >::get_height () [inline]
Definition at line 990 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Granularity> const size_type stxxl::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, 0, Granularity >::get_width () [inline]
Definition at line 993 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, unsigned Granularity> swappable_block_matrix_type stxxl::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, 0, Granularity >::operator() (const size_type & row, const size_type & col) [inline]
Definition at line 985 of file matrix_arithmetic.h.
Member Data Documentation
template<typename ValueType , unsigned BlockSideLength, unsigned Granularity> swappable_block_matrix_type stxxl::matrix_to_quadtree_block_grained< ValueType, BlockSideLength, 0, Granularity >::m
Definition at line 974 of file matrix_arithmetic.h.
The documentation for this struct was generated from the following file:
include/stxxl/bits/containers/matrix_arithmetic.h