Stxxl: stxxl::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists > Struct Template Reference
stxxl::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists > Struct Template Reference
#include <matrix_arithmetic.h>
Public Types
typedef swappable_block_matrix
< ValueType, BlockSideLength > swappable_block_matrix_type
typedef
swappable_block_matrix_type::block_scheduler_type block_scheduler_type
typedef
swappable_block_matrix_type::swappable_block_identifier_type swappable_block_identifier_type
typedef
swappable_block_matrix_type::size_type size_type
typedef matrix_operations
< ValueType, BlockSideLength > Ops
typedef static_quadtree
< swappable_block_identifier_type, 0 > bt
Public Member Functions
feedable_strassen_winograd_block_grained (const swappable_block_matrix_type &existing_a, const size_type a_from_row, const size_type a_from_col, block_scheduler_type &bs_c, const size_type n, const size_type m, const size_type l, const swappable_block_matrix_type &existing_b, const size_type b_from_row, const size_type b_from_col)
feedable_strassen_winograd_block_grained (const swappable_block_matrix_type &existing_a, const size_type a_from_row, const size_type a_from_col, block_scheduler_type &bs_c, const size_type n, const size_type m, const size_type l)
feedable_strassen_winograd_block_grained (block_scheduler_type &bs_c, const size_type n, const size_type m, const size_type l, const swappable_block_matrix_type &existing_b, const size_type b_from_row, const size_type b_from_col)
feedable_strassen_winograd_block_grained (block_scheduler_type &bs_c, const size_type n, const size_type m, const size_type l)
void feed_a (const size_type &row, const size_type &col, const swappable_block_matrix_type &bl)
void feed_b (const size_type &row, const size_type &col, const swappable_block_matrix_type &bl)
void multiply ()
void read_and_add (const size_type &row, const size_type &col, swappable_block_matrix_type &bl)
Static Public Member Functions
static unsigned_type get_num_temp_grains ()
Public Attributes
swappable_block_matrix_type a
swappable_block_matrix_type b
swappable_block_matrix_type c
Detailed Description
template<typename ValueType, unsigned BlockSideLength, bool AExists, bool BExists>
struct stxxl::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >
Definition at line 848 of file matrix_arithmetic.h.
Member Typedef Documentation
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> typedef swappable_block_matrix_type::block_scheduler_type stxxl::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::block_scheduler_type
Definition at line 851 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> typedef static_quadtree<swappable_block_identifier_type, 0> stxxl::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::bt
Definition at line 856 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> typedef matrix_operations<ValueType, BlockSideLength> stxxl::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::Ops
Definition at line 854 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> typedef swappable_block_matrix_type::size_type stxxl::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::size_type
Definition at line 853 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> typedef swappable_block_matrix_type::swappable_block_identifier_type stxxl::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::swappable_block_identifier_type
Definition at line 852 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> typedef swappable_block_matrix<ValueType, BlockSideLength> stxxl::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::swappable_block_matrix_type
Definition at line 850 of file matrix_arithmetic.h.
Constructor & Destructor Documentation
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> stxxl::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::feedable_strassen_winograd_block_grained (const swappable_block_matrix_type & existing_a, const size_type a_from_row, const size_type a_from_col, block_scheduler_type & bs_c, const size_type n, const size_type m, const size_type l, const swappable_block_matrix_type & existing_b, const size_type b_from_row, const size_type b_from_col) [inline]
Definition at line 860 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> stxxl::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::feedable_strassen_winograd_block_grained (const swappable_block_matrix_type & existing_a, const size_type a_from_row, const size_type a_from_col, block_scheduler_type & bs_c, const size_type n, const size_type m, const size_type l) [inline]
Definition at line 868 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> stxxl::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::feedable_strassen_winograd_block_grained (block_scheduler_type & bs_c, const size_type n, const size_type m, const size_type l, const swappable_block_matrix_type & existing_b, const size_type b_from_row, const size_type b_from_col) [inline]
Definition at line 875 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> stxxl::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::feedable_strassen_winograd_block_grained (block_scheduler_type & bs_c, const size_type n, const size_type m, const size_type l) [inline]
Definition at line 882 of file matrix_arithmetic.h.
Member Function Documentation
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> void stxxl::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::feed_a (const size_type & row, const size_type & col, const swappable_block_matrix_type & bl) [inline]
Definition at line 888 of file matrix_arithmetic.h.
References stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_height(), and stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_width().
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> void stxxl::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::feed_b (const size_type & row, const size_type & col, const swappable_block_matrix_type & bl) [inline]
Definition at line 898 of file matrix_arithmetic.h.
References stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_height(), and stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_width().
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> static unsigned_type stxxl::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::get_num_temp_grains () [inline, static]
Definition at line 927 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> void stxxl::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::multiply () [inline]
Definition at line 908 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> void stxxl::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::read_and_add (const size_type & row, const size_type & col, swappable_block_matrix_type & bl) [inline]
Definition at line 919 of file matrix_arithmetic.h.
References stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_height(), and stxxl::swappable_block_matrix< ValueType, BlockSideLength >::get_width().
Member Data Documentation
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> swappable_block_matrix_type stxxl::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::a
Definition at line 858 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> swappable_block_matrix_type stxxl::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::b
Definition at line 858 of file matrix_arithmetic.h.
template<typename ValueType , unsigned BlockSideLength, bool AExists, bool BExists> swappable_block_matrix_type stxxl::feedable_strassen_winograd_block_grained< ValueType, BlockSideLength, 0, AExists, BExists >::c
Definition at line 858 of file matrix_arithmetic.h.
The documentation for this struct was generated from the following file:
include/stxxl/bits/containers/matrix_arithmetic.h