Stxxl: mng/test_aligned.cpp File Reference
mng/test_aligned.cpp File Reference
#include <iostream>
#include <vector>
#include <stxxl/mng>
Defines
#define STXXL_VERBOSE_LEVEL 0
#define STXXL_VERBOSE_ALIGNED_ALLOC STXXL_VERBOSE0
#define STXXL_VERBOSE_TYPED_BLOCK STXXL_VERBOSE0
#define BLOCK_SIZE (1024 * 1024)
Typedefs
typedef stxxl::typed_block
< (1024 *1024), type block_type)
Functions
void test_typed_block ()
void test_aligned_alloc ()
void test_typed_block_vector ()
int main ()
Define Documentation
#define BLOCK_SIZE (1024 * 1024)
Examples:
containers/pq_benchmark.cpp, containers/stack_benchmark.cpp, containers/tpie_stack_benchmark.cpp, and mng/test_mng.cpp.
Definition at line 21 of file test_aligned.cpp.
#define STXXL_VERBOSE_ALIGNED_ALLOC STXXL_VERBOSE0
Definition at line 14 of file test_aligned.cpp.
#define STXXL_VERBOSE_LEVEL 0
Definition at line 13 of file test_aligned.cpp.
#define STXXL_VERBOSE_TYPED_BLOCK STXXL_VERBOSE0
Definition at line 15 of file test_aligned.cpp.
Typedef Documentation
typedef stxxl::typed_block< (1024 * 1024) , type block_type)
Examples:
containers/pq_benchmark.cpp, containers/stack_benchmark.cpp, containers/test_pqueue.cpp, mng/test_buf_streams.cpp, mng/test_mng.cpp, mng/test_pool_pair.cpp, mng/test_prefetch_pool.cpp, mng/test_read_write_pool.cpp, and mng/test_write_pool.cpp.
Definition at line 29 of file test_aligned.cpp.
Function Documentation
int main ()
Definition at line 65 of file test_aligned.cpp.
References STXXL_MSG, test_aligned_alloc(), test_typed_block(), and test_typed_block_vector().
void test_aligned_alloc ()
Definition at line 49 of file test_aligned.cpp.
Referenced by main().
void test_typed_block ()
Definition at line 31 of file test_aligned.cpp.
References C().
Referenced by main().
void test_typed_block_vector ()
Definition at line 59 of file test_aligned.cpp.
Referenced by main().