Stxxl: containers/test_ext_merger.cpp File Reference
containers/test_ext_merger.cpp File Reference
#include <limits>
#include <iterator>
#include <stxxl/priority_queue>
Typedefs
typedef int my_type
typedef stxxl::typed_block
< 4096, my_type > block_type
Functions
my_type * make_sequence (dummy_merger &dummy, int l)
int main ()
Typedef Documentation
typedef stxxl::typed_block<4096, my_type> block_type
Definition at line 22 of file test_ext_merger.cpp.
typedef int my_type
Definition at line 21 of file test_ext_merger.cpp.
Function Documentation
int main ()
Definition at line 61 of file test_ext_merger.cpp.
References dummy, stxxl::priority_queue_local::loser_tree< ValTp_, Cmp_, KNKMAX >::init(), stxxl::priority_queue_local::loser_tree< ValTp_, Cmp_, KNKMAX >::insert_segment(), stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::insert_segment(), make_sequence(), stxxl::priority_queue_local::loser_tree< ValTp_, Cmp_, KNKMAX >::multi_merge(), and stxxl::priority_queue_local::ext_merger< BlockType_, Cmp_, Arity_, AllocStr_ >::multi_merge().
my_type* make_sequence (dummy_merger & dummy, int l)
Definition at line 53 of file test_ext_merger.cpp.
Referenced by main().