Stxxl: containers/test_vector_export.cpp File Reference
containers/test_vector_export.cpp File Reference
#include <iostream>
#include <algorithm>
#include <stxxl/vector>
#include <stxxl/scan>
Typedefs
typedef stxxl::int64 int64
Functions
int main ()
Typedef Documentation
typedef stxxl::int64 int64
Examples:
algo/test_scan.cpp, and containers/test_vector_export.cpp.
Definition at line 21 of file test_vector_export.cpp.
Function Documentation
int main ()
Definition at line 24 of file test_vector_export.cpp.
References stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::export_files(), stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::flush(), stxxl::ran32State, stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::size(), and STXXL_MSG.