Stxxl: mng/test_block_alloc_strategy.cpp File Reference
mng/test_block_alloc_strategy.cpp File Reference
#include <stxxl/mng>
#include <stxxl/bits/mng/block_alloc_interleaved.h>
#include <stxxl/bits/common/error_handling.h>
Functions
template<typename strategy >
void test_strategy ()
int main ()
Function Documentation
int main ()
Definition at line 45 of file test_block_alloc_strategy.cpp.
References stxxl::config::disk_io_impl(), stxxl::config::disk_path(), stxxl::config::disk_size(), stxxl::config::disks_number(), stxxl::config::flash_range(), stxxl::config::regular_disk_range(), and STXXL_MSG.
template<typename strategy > void test_strategy ()
Definition at line 20 of file test_block_alloc_strategy.cpp.
References STXXL_MSG, and STXXL_PRETTY_FUNCTION_NAME.