Stxxl: containers/test_map_random.cpp File Reference
containers/test_map_random.cpp File Reference
File for testing functionality of stxxl::map.
#include <stxxl/map>
#include "map_test_handlers.h"
Defines
#define DATA_NODE_BLOCK_SIZE (4096)
#define DATA_LEAF_BLOCK_SIZE (4096)
#define PERCENT_CLEAR 1
#define PERCENT_ERASE_BULK 9
#define PERCENT_ERASE_KEY 90
#define PERCENT_ERASE_ITERATOR 100
#define PERCENT_INSERT_PAIR 100
#define PERCENT_INSERT_BULK 100
#define PERCENT_SIZING 100
#define PERCENT_LOWER 100
#define PERCENT_UPPER 200
#define PERCENT_FIND 100
#define PERCENT_ITERATOR 100
#define MAX_KEY 10000
#define NODE_BLOCK_SIZE xxl_map_type::node_block_type::raw_size
#define LEAF_BLOCK_SIZE xxl_map_type::leaf_block_type::raw_size
#define NODE_MELEMENTS xxl_map_type::node_block_type::size
#define LEAF_MELEMENTS xxl_map_type::leaf_block_type::size
Typedefs
typedef int key_type
typedef int data_type
typedef std::map< key_type,
data_type, cmp2 > std_map_type
typedef stxxl::map< key_type,
data_type, cmp2,(4096),(4096) > xxl_map_type
Functions
int main (int argc, char *argv[])
Detailed Description
File for testing functionality of stxxl::map.
Definition in file test_map_random.cpp.
Define Documentation
#define DATA_LEAF_BLOCK_SIZE (4096)
Examples:
containers/test_map_random.cpp.
Definition at line 36 of file test_map_random.cpp.
#define DATA_NODE_BLOCK_SIZE (4096)
Examples:
containers/test_map_random.cpp.
Definition at line 35 of file test_map_random.cpp.
#define LEAF_BLOCK_SIZE xxl_map_type::leaf_block_type::raw_size
Definition at line 61 of file test_map_random.cpp.
Referenced by main().
#define LEAF_MELEMENTS xxl_map_type::leaf_block_type::size
Examples:
containers/test_map_random.cpp.
Definition at line 63 of file test_map_random.cpp.
Referenced by main().
#define MAX_KEY 10000
Examples:
containers/test_map_random.cpp.
Definition at line 56 of file test_map_random.cpp.
Referenced by main().
#define NODE_BLOCK_SIZE xxl_map_type::node_block_type::raw_size
Definition at line 60 of file test_map_random.cpp.
Referenced by main().
#define NODE_MELEMENTS xxl_map_type::node_block_type::size
Examples:
containers/test_map_random.cpp.
Definition at line 62 of file test_map_random.cpp.
Referenced by main().
#define PERCENT_CLEAR 1
Examples:
containers/test_map_random.cpp.
Definition at line 42 of file test_map_random.cpp.
Referenced by main().
#define PERCENT_ERASE_BULK 9
Examples:
containers/test_map_random.cpp.
Definition at line 43 of file test_map_random.cpp.
Referenced by main().
#define PERCENT_ERASE_ITERATOR 100
Examples:
containers/test_map_random.cpp.
Definition at line 45 of file test_map_random.cpp.
Referenced by main().
#define PERCENT_ERASE_KEY 90
Examples:
containers/test_map_random.cpp.
Definition at line 44 of file test_map_random.cpp.
Referenced by main().
#define PERCENT_FIND 100
Examples:
containers/test_map_random.cpp.
Definition at line 51 of file test_map_random.cpp.
Referenced by main().
#define PERCENT_INSERT_BULK 100
Examples:
containers/test_map_random.cpp.
Definition at line 47 of file test_map_random.cpp.
Referenced by main().
#define PERCENT_INSERT_PAIR 100
Examples:
containers/test_map_random.cpp.
Definition at line 46 of file test_map_random.cpp.
Referenced by main().
#define PERCENT_ITERATOR 100
Examples:
containers/test_map_random.cpp.
Definition at line 52 of file test_map_random.cpp.
Referenced by main().
#define PERCENT_LOWER 100
Examples:
containers/test_map_random.cpp.
Definition at line 49 of file test_map_random.cpp.
Referenced by main().
#define PERCENT_SIZING 100
Examples:
containers/test_map_random.cpp.
Definition at line 48 of file test_map_random.cpp.
Referenced by main().
#define PERCENT_UPPER 200
Examples:
containers/test_map_random.cpp.
Definition at line 50 of file test_map_random.cpp.
Referenced by main().
Typedef Documentation
typedef int data_type
Definition at line 25 of file test_map_random.cpp.
typedef int key_type
Definition at line 24 of file test_map_random.cpp.
typedef std::map<key_type, data_type, cmp2> std_map_type
Examples:
containers/test_map_random.cpp.
Definition at line 38 of file test_map_random.cpp.
typedef stxxl::map<key_type, data_type, cmp2, (4096) , (4096) > xxl_map_type
Examples:
containers/test_map_random.cpp.
Definition at line 40 of file test_map_random.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 65 of file test_map_random.cpp.
References stxxl::map< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::begin(), stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::begin(), stxxl::map< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::clear(), stxxl::map< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::empty(), stxxl::map< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::end(), stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::end(), stxxl::map< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::erase(), stxxl::map< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::find(), stxxl::map< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::insert(), stxxl::is_end(), stxxl::is_same(), LEAF_BLOCK_SIZE, LEAF_MELEMENTS, stxxl::map< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::lower_bound(), MAX_KEY, NODE_BLOCK_SIZE, NODE_MELEMENTS, stxxl::not_there(), PERCENT_CLEAR, PERCENT_ERASE_BULK, PERCENT_ERASE_ITERATOR, PERCENT_ERASE_KEY, PERCENT_FIND, PERCENT_INSERT_BULK, PERCENT_INSERT_PAIR, PERCENT_ITERATOR, PERCENT_LOWER, PERCENT_SIZING, PERCENT_UPPER, stxxl::ran32State, stxxl::map< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::size(), STXXL_MSG, std::swap(), stxxl::there(), and stxxl::map< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::upper_bound().