Stxxl: containers/test_vector.cpp File Reference
containers/test_vector.cpp File Reference
#include <iostream>
#include <algorithm>
#include <stxxl/vector>
#include <stxxl/scan>
Functions
template<class my_vec_type >
void test_const_iterator (const my_vec_type &x)
int main ()
Function Documentation
int main ()
Definition at line 72 of file test_vector.cpp.
References stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::begin(), stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::clear(), stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::end(), stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::flush(), stxxl::generate(), stxxl::ran32State, stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::resize(), stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::size(), STXXL_MSG, std::swap(), and test_const_iterator().
template<class my_vec_type > void test_const_iterator (const my_vec_type & x)
Examples:
containers/test_vector.cpp.
Definition at line 58 of file test_vector.cpp.
Referenced by main().