Stxxl: mng/test_block_scheduler.cpp File Reference
mng/test_block_scheduler.cpp File Reference
#include <stxxl/bits/mng/block_scheduler.h>
#include <Argument_helper.h>
#include <iostream>
#include <limits>
Functions
template<class IBT >
void set_pattern_A (IBT &ib)
template<class IBT >
int_type test_pattern_A (IBT &ib)
template<class IBT >
void set_pattern_B (IBT &ib)
template<class IBT >
int_type test_pattern_B (IBT &ib)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 55 of file test_block_scheduler.cpp.
References stxxl::block_scheduler_algorithm_simulation< SwappableBlockType >::acquire(), block_size, set_pattern_A(), STXXL_MSG, test_pattern_A(), and test_pattern_B().
template<class IBT > void set_pattern_A (IBT & ib)
Definition at line 24 of file test_block_scheduler.cpp.
Referenced by main().
template<class IBT > void set_pattern_B (IBT & ib)
Definition at line 40 of file test_block_scheduler.cpp.
template<class IBT > int_type test_pattern_A (IBT & ib)
Definition at line 31 of file test_block_scheduler.cpp.
Referenced by main().
template<class IBT > int_type test_pattern_B (IBT & ib)
Definition at line 47 of file test_block_scheduler.cpp.
Referenced by main().