Stxxl: algo/test_sort_all_parameters.cpp File Reference
algo/test_sort_all_parameters.cpp File Reference
#include <stxxl/mng>
#include <stxxl/sort>
#include <stxxl/scan>
#include <stxxl/vector>
#include <stxxl/random>
#include "test_sort_all_parameters.h"
Defines
#define RECORD_SIZE 4
#define MB (1024 * 1024)
Functions
template<typename T , typename alloc_strategy_type , unsigned block_size>
void test (stxxl::uint64 data_mem, unsigned memory_to_use)
template<typename T , unsigned block_size>
void test_all_strategies (stxxl::uint64 data_mem, unsigned memory_to_use, int strategy)
int main (int argc, char *argv[])
Define Documentation
#define MB (1024 * 1024)
Definition at line 29 of file test_sort_all_parameters.cpp.
Referenced by main(), and test().
#define RECORD_SIZE 4
Definition at line 26 of file test_sort_all_parameters.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 91 of file test_sort_all_parameters.cpp.
References stxxl::atoint64(), block_size, stxxl::get_next_seed(), MB, stxxl::set_seed(), stxxl::srandom_number32(), and STXXL_MSG.
template<typename T , typename alloc_strategy_type , unsigned block_size> void test (stxxl::uint64 data_mem, unsigned memory_to_use)
Definition at line 33 of file test_sort_all_parameters.cpp.
References stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::begin(), block_size, stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::end(), stxxl::generate(), stxxl::is_sorted(), MB, stxxl::typed_block< RawSize_, T_, NRef_, InfoType_ >::raw_size, stxxl::sort(), and STXXL_MSG.
template<typename T , unsigned block_size> void test_all_strategies (stxxl::uint64 data_mem, unsigned memory_to_use, int strategy)
Definition at line 66 of file test_sort_all_parameters.cpp.
References memory_to_use.