Stxxl: containers/btree/test_corr_insert_scan.cpp File Reference
containers/btree/test_corr_insert_scan.cpp File Reference
#include <iostream>
#include <stxxl/bits/containers/btree/btree.h>
#include <stxxl/scan>
#include <stxxl/sort>
Typedefs
typedef stxxl::btree::btree
< int, double, comp_type,
4096, 4096, stxxl::SR > btree_type
Functions
std::ostream & operator<< (std::ostream &o, const std::pair< int, double > &obj)
bool operator== (const std::pair< int, double > &a, const std::pair< int, double > &b)
int main (int argc, char *argv[])
Typedef Documentation
typedef stxxl::btree::btree<int, double, comp_type, 4096, 4096, stxxl::SR> btree_type
Definition at line 32 of file test_corr_insert_scan.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 56 of file test_corr_insert_scan.cpp.
References stxxl::btree::btree< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::begin(), stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::begin(), stxxl::btree::btree< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::end(), stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::end(), stxxl::generate(), stxxl::btree::btree< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::insert(), stxxl::ran32State, stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::resize(), stxxl::btree::btree< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::size(), stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::size(), stxxl::sort(), and STXXL_MSG.
std::ostream& operator<< (std::ostream & o, const std::pair< int, double > & obj)
Definition at line 35 of file test_corr_insert_scan.cpp.
bool operator== (const std::pair< int, double > & a, const std::pair< int, double > & b)
Definition at line 51 of file test_corr_insert_scan.cpp.