Stxxl: containers/test_vector_sizes.cpp File Reference
containers/test_vector_sizes.cpp File Reference
#include <stxxl/io>
#include <stxxl/vector>
Typedefs
typedef int my_type
typedef
stxxl::VECTOR_GENERATOR
< my_type >::result vector_type
typedef vector_type::block_type block_type
Functions
void test_write (const char *fn, const char *ft, stxxl::unsigned_type sz, my_type ofs)
template<typename Vector >
void test_rdwr (const char *fn, const char *ft, stxxl::unsigned_type sz, my_type ofs)
template<typename Vector >
void test_rdonly (const char *fn, const char *ft, stxxl::unsigned_type sz, my_type ofs)
void test (const char *fn, const char *ft, stxxl::unsigned_type sz, my_type ofs)
int main (int argc, char **argv)
Typedef Documentation
typedef vector_type::block_type block_type
Definition at line 19 of file test_vector_sizes.cpp.
typedef int my_type
Definition at line 17 of file test_vector_sizes.cpp.
typedef stxxl::VECTOR_GENERATOR<my_type>::result vector_type
Definition at line 18 of file test_vector_sizes.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 71 of file test_vector_sizes.cpp.
References stxxl::file::DIRECT, stxxl::file::RDWR, stxxl::ufs_file_base::set_size(), stxxl::ufs_file_base::size(), STXXL_MSG, and test().
void test (const char * fn, const char * ft, stxxl::unsigned_type sz, my_type ofs)
Definition at line 62 of file test_vector_sizes.cpp.
References test_write().
template<typename Vector > void test_rdonly (const char * fn, const char * ft, stxxl::unsigned_type sz, my_type ofs)
Definition at line 49 of file test_vector_sizes.cpp.
References stxxl::create_file(), stxxl::file::DIRECT, stxxl::file::RDONLY, and STXXL_MSG.
template<typename Vector > void test_rdwr (const char * fn, const char * ft, stxxl::unsigned_type sz, my_type ofs)
Definition at line 35 of file test_vector_sizes.cpp.
References stxxl::create_file(), stxxl::file::DIRECT, stxxl::file::RDWR, and STXXL_MSG.
void test_write (const char * fn, const char * ft, stxxl::unsigned_type sz, my_type ofs)
Definition at line 21 of file test_vector_sizes.cpp.
References stxxl::file::CREAT, stxxl::create_file(), stxxl::file::DIRECT, stxxl::file::RDWR, stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::resize(), stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::size(), and STXXL_MSG.
Referenced by test().