Stxxl: containers/btree/test_const_scan.cpp File Reference
containers/btree/test_const_scan.cpp File Reference
#include <iostream>
#include <stxxl/bits/containers/btree/btree.h>
#include <stxxl/timer>
Defines
#define NODE_BLOCK_SIZE 4096
#define LEAF_BLOCK_SIZE 128 * 1024
#define node_cache_size (25 * 1024 * 1024)
#define leaf_cache_size (6 * LEAF_BLOCK_SIZE)
Typedefs
typedef stxxl::btree::btree
< int, my_type, comp_type,
4096, 128 *1024, stxxl::SR > btree_type
Functions
std::ostream & operator<< (std::ostream &o, const my_type &obj)
std::ostream & operator<< (std::ostream &o, const std::pair< int, double > &obj)
void NC (btree_type &BTree)
void C (btree_type &BTree)
int main (int argc, char *argv[])
Define Documentation
#define LEAF_BLOCK_SIZE 128 * 1024
Definition at line 28 of file test_const_scan.cpp.
#define leaf_cache_size (6 * LEAF_BLOCK_SIZE)
Definition at line 52 of file test_const_scan.cpp.
Referenced by main().
#define NODE_BLOCK_SIZE 4096
Definition at line 27 of file test_const_scan.cpp.
#define node_cache_size (25 * 1024 * 1024)
Definition at line 51 of file test_const_scan.cpp.
Referenced by main().
Typedef Documentation
typedef stxxl::btree::btree<int, my_type, comp_type, 4096 , 128 * 1024 , stxxl::SR> btree_type
Definition at line 49 of file test_const_scan.cpp.
Function Documentation
void C (btree_type & BTree)
Definition at line 68 of file test_const_scan.cpp.
References stxxl::btree::btree< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::begin(), stxxl::btree::btree< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::end(), stxxl::timer::mseconds(), stxxl::timer::start(), stxxl::timer::stop(), and STXXL_MSG.
Referenced by stxxl::matrix_operations< ValueType, BlockSideLength >::choose_level_for_feedable_sw(), stxxl::matrix_operations< ValueType, BlockSideLength >::element_op(), main(), stxxl::matrix_operations< ValueType, BlockSideLength >::multi_level_strassen_winograd_multiply_and_add(), stxxl::matrix_operations< ValueType, BlockSideLength >::multi_level_strassen_winograd_multiply_and_add_block_grained(), stxxl::matrix< ValueType, BlockSideLength >::multiply_internal(), stxxl::matrix_operations< ValueType, BlockSideLength >::naive_multiply_and_add(), stxxl::matrix_operations< ValueType, BlockSideLength >::recursive_multiply_and_add(), stxxl::matrix_operations< ValueType, BlockSideLength >::strassen_winograd_multiply(), stxxl::matrix_operations< ValueType, BlockSideLength >::strassen_winograd_multiply_and_add(), stxxl::matrix_operations< ValueType, BlockSideLength >::strassen_winograd_multiply_and_add_interleaved(), test_typed_block(), and stxxl::shared_object_pointer< swappable_block_matrix_type >::unify().
int main (int argc, char * argv[])
Definition at line 82 of file test_const_scan.cpp.
References C(), leaf_cache_size, NC(), node_cache_size, and STXXL_MSG.
void NC (btree_type & BTree)
Definition at line 54 of file test_const_scan.cpp.
References stxxl::btree::btree< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::begin(), stxxl::btree::btree< KeyType, DataType, CompareType, RawNodeSize, RawLeafSize, PDAllocStrategy >::end(), stxxl::timer::mseconds(), stxxl::timer::start(), stxxl::timer::stop(), and STXXL_MSG.
Referenced by main().
std::ostream& operator<< (std::ostream & o, const my_type & obj)
Definition at line 36 of file test_const_scan.cpp.
std::ostream& operator<< (std::ostream & o, const std::pair< int, double > & obj)
Definition at line 42 of file test_const_scan.cpp.