Stxxl: io/test_io_sizes.cpp File Reference
io/test_io_sizes.cpp File Reference
#include <stxxl/io>
#include <stxxl/aligned_alloc>
#include <stxxl/bits/mng/mng.h>
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 21 of file test_io_sizes.cpp.
References stxxl::add_IEC_binary_multiplier(), stxxl::atoint64(), stxxl::file::CREAT, stxxl::create_file(), stxxl::file::DIRECT, stxxl::file::RDWR, STXXL_MSG, and stxxl::wait_all().