Stxxl: stream/test_stream.cpp File Reference
stream/test_stream.cpp File Reference
#include <limits>
#include <vector>
#include <stxxl/stream>
#include <stxxl/vector>
Namespaces
namespace std
Defines
#define USE_FORMRUNS_N_MERGE
#define USE_EXTERNAL_ARRAY
#define block_size (8 * 1024)
Typedefs
typedef stxxl::tuple< char, int > tuple_type
typedef
stxxl::VECTOR_GENERATOR< char >
::result input_array_type
typedef
stxxl::VECTOR_GENERATOR
< tuple_type >::result output_array_type
typedef counter< int > counter_type
Functions
std::ostream & std::operator<< (std::ostream &os, const tuple_type &t)
template<class Container_ , class It_ >
void fill_input_array (Container_ &container, It_ p)
int main ()
Variables
const char * phrase = "Hasta la vista, baby"
Define Documentation
#define block_size (8 * 1024)
Examples:
algo/copy_and_sort_file.cpp, algo/sort_file.cpp, algo/test_parallel_sort.cpp, containers/test_sorter.cpp, stream/test_push_sort.cpp, and stream/test_sorted_runs.cpp.
Definition at line 32 of file test_stream.cpp.
Referenced by stxxl::DiskAllocator::add_free_region(), main(), and test().
#define USE_EXTERNAL_ARRAY
Definition at line 29 of file test_stream.cpp.
#define USE_FORMRUNS_N_MERGE
Definition at line 26 of file test_stream.cpp.
Typedef Documentation
typedef counter<int> counter_type
Examples:
stream/test_stream.cpp.
Definition at line 88 of file test_stream.cpp.
typedef stxxl::VECTOR_GENERATOR<char>::result input_array_type
Examples:
stream/test_stream.cpp.
Definition at line 46 of file test_stream.cpp.
typedef stxxl::VECTOR_GENERATOR<tuple_type>::result output_array_type
Examples:
stream/test_stream.cpp.
Definition at line 47 of file test_stream.cpp.
typedef stxxl::tuple<char, int> tuple_type
Examples:
stream/test_stream.cpp.
Definition at line 34 of file test_stream.cpp.
Function Documentation
template<class Container_ , class It_ > void fill_input_array (Container_ & container, It_ p)
Examples:
stream/test_stream.cpp.
Definition at line 63 of file test_stream.cpp.
Referenced by main().
int main ()
Definition at line 137 of file test_stream.cpp.
References stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::begin(), stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::end(), fill_input_array(), stxxl::stream::materialize(), phrase, stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::resize(), stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::size(), stxxl::sort(), stxxl::stream::streamify(), and STXXL_MSG.
Variable Documentation
const char* phrase = "Hasta la vista, baby"
Examples:
stream/test_stream.cpp.
Definition at line 59 of file test_stream.cpp.
Referenced by main().