Stxxl: containers/test_iterators.cpp File Reference
containers/test_iterators.cpp File Reference
#include <cassert>
#include <cstring>
#include <deque>
#include <map>
#include <vector>
#include <stxxl.h>
Defines
#define GCC_VERSION (__GNUC__ * 10000 + __GNUC_MINOR__ * 100)
Typedefs
typedef float key_type
typedef double data_type
Functions
template<typename T >
const char * _ ()
template<typename I >
void dump_iterator_info (I &)
template<typename C >
void dump_container_info (C &)
template<typename Iterator >
bool test_inc_dec (Iterator it)
template<typename Iterator >
bool test_inc_dec_random (Iterator it)
template<typename IteratorA , typename IteratorB >
void test_comparison (IteratorA a, IteratorB b)
template<typename Iterator >
void test_operators (Iterator it)
template<typename svt >
void test (svt &sv)
template<typename svt >
void test_reverse (svt &sv)
template<typename svt >
void test_random_access (svt &sv)
template<typename svt >
void test_random_access_reverse (svt &sv)
int main ()
Define Documentation
#define GCC_VERSION (__GNUC__ * 10000 + __GNUC_MINOR__ * 100)
Definition at line 22 of file test_iterators.cpp.
Typedef Documentation
typedef double data_type
Examples:
containers/test_map_random.cpp.
Definition at line 349 of file test_iterators.cpp.
typedef float key_type
Examples:
algo/copy_and_sort_file.cpp, algo/sort_file.cpp, algo/test_bad_cmp.cpp, algo/test_ksort.cpp, algo/test_parallel_sort.cpp, algo/test_sort.cpp, algo/test_stable_ksort.cpp, containers/test_map_random.cpp, containers/test_pqueue.cpp, and containers/test_sorter.cpp.
Definition at line 348 of file test_iterators.cpp.
Function Documentation
template<typename T > const char* _ ()
Definition at line 25 of file test_iterators.cpp.
References STXXL_PRETTY_FUNCTION_NAME.
Referenced by dump_iterator_info().
template<typename C > void dump_container_info (C &)
Definition at line 46 of file test_iterators.cpp.
References STXXL_MSG, and STXXL_PRETTY_FUNCTION_NAME.
Referenced by test(), and test_reverse().
template<typename I > void dump_iterator_info (I &)
Definition at line 35 of file test_iterators.cpp.
References _(), STXXL_MSG, and STXXL_PRETTY_FUNCTION_NAME.
Referenced by test(), and test_reverse().
int main ()
Definition at line 373 of file test_iterators.cpp.
References D(), test(), test_random_access(), test_random_access_reverse(), and test_reverse().
template<typename svt > void test (svt & sv)
Definition at line 148 of file test_iterators.cpp.
References dump_container_info(), dump_iterator_info(), test_comparison(), test_inc_dec(), and test_operators().
Referenced by main().
template<typename IteratorA , typename IteratorB > void test_comparison (IteratorA a, IteratorB b)
Definition at line 128 of file test_iterators.cpp.
Referenced by test(), test_operators(), and test_reverse().
template<typename Iterator > bool test_inc_dec (Iterator it)
Definition at line 70 of file test_iterators.cpp.
Referenced by test(), and test_reverse().
template<typename Iterator > bool test_inc_dec_random (Iterator it)
Definition at line 84 of file test_iterators.cpp.
Referenced by test_random_access(), and test_random_access_reverse().
template<typename Iterator > void test_operators (Iterator it)
Definition at line 140 of file test_iterators.cpp.
References test_comparison().
Referenced by test(), and test_reverse().
template<typename svt > void test_random_access (svt & sv)
Definition at line 304 of file test_iterators.cpp.
References test_inc_dec_random().
Referenced by main().
template<typename svt > void test_random_access_reverse (svt & sv)
Definition at line 325 of file test_iterators.cpp.
References test_inc_dec_random().
Referenced by main().
template<typename svt > void test_reverse (svt & sv)
Definition at line 223 of file test_iterators.cpp.
References dump_container_info(), dump_iterator_info(), test_comparison(), test_inc_dec(), and test_operators().
Referenced by main().