Stxxl: mng/test_buf_streams.cpp File Reference
mng/test_buf_streams.cpp File Reference
#include <iostream>
#include <stxxl/mng>
#include <stxxl/bits/mng/buf_ostream.h>
#include <stxxl/bits/mng/buf_istream.h>
Defines
#define BLOCK_SIZE (1024 * 512)
Typedefs
typedef stxxl::typed_block
< (1024 *512), unsigned block_type)
typedef stxxl::buf_ostream
< block_type, stxxl::BIDArray
< (1024 *512) >::iterator buf_ostream_type)
typedef stxxl::buf_istream
< block_type, stxxl::BIDArray
< (1024 *512) >::iterator buf_istream_type)
Functions
int main ()
Define Documentation
#define BLOCK_SIZE (1024 * 512)
Definition at line 22 of file test_buf_streams.cpp.
Typedef Documentation
typedef stxxl::typed_block< (1024 * 512) , unsigned block_type)
Definition at line 24 of file test_buf_streams.cpp.
typedef stxxl::buf_istream<block_type, stxxl::BIDArray< (1024 * 512) >::iterator buf_istream_type)
Examples:
mng/test_buf_streams.cpp.
Definition at line 26 of file test_buf_streams.cpp.
typedef stxxl::buf_ostream<block_type, stxxl::BIDArray< (1024 * 512) >::iterator buf_ostream_type)
Examples:
mng/test_buf_streams.cpp.
Definition at line 25 of file test_buf_streams.cpp.
Function Documentation
int main ()
Definition at line 28 of file test_buf_streams.cpp.
References stxxl::BIDArray< BLK_SIZE >::begin(), stxxl::block_manager::delete_blocks(), stxxl::BIDArray< BLK_SIZE >::end(), and stxxl::block_manager::new_blocks().