Stxxl: stream/test_push_sort.cpp File Reference
stream/test_push_sort.cpp File Reference
#include <limits>
#include <stxxl/stream>
Typedefs
typedef unsigned value_type
Functions
int main ()
Variables
const unsigned long long megabyte = 1024 * 1024
const unsigned int block_size = 1 * megabyte
Typedef Documentation
typedef unsigned value_type
Examples:
containers/berkeley_db_benchmark.cpp, containers/stack_benchmark.cpp, containers/test_matrix.cpp, stream/test_loop.cpp, stream/test_naive_transpose.cpp, stream/test_push_sort.cpp, stream/test_sorted_runs.cpp, and stream/test_stream.cpp.
Definition at line 26 of file test_push_sort.cpp.
Function Documentation
int main ()
Definition at line 45 of file test_push_sort.cpp.
References stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::begin(), block_size, stxxl::stream::check_sorted_runs(), stxxl::stream::basic_runs_merger< RunsType_, CompareType_, AllocStr_ >::empty(), stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::end(), stxxl::is_sorted(), megabyte, stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::push_back(), STXXL_DEFAULT_ALLOC_STRATEGY, and STXXL_MSG.
Variable Documentation
const unsigned int block_size = 1 * megabyte
Definition at line 24 of file test_push_sort.cpp.
const unsigned long long megabyte = 1024 * 1024
Definition at line 23 of file test_push_sort.cpp.