Stxxl: algo/test_sort.cpp File Reference
algo/test_sort.cpp File Reference
#include <stxxl/mng>
#include <stxxl/sort>
#include <stxxl/vector>
Defines
#define RECORD_SIZE 8
Functions
std::ostream & operator<< (std::ostream &o, const my_type &obj)
bool operator< (const my_type &a, const my_type &b)
bool operator== (const my_type &a, const my_type &b)
bool operator!= (const my_type &a, const my_type &b)
int main ()
Define Documentation
#define RECORD_SIZE 8
Definition at line 22 of file test_sort.cpp.
Function Documentation
int main ()
Definition at line 84 of file test_sort.cpp.
References stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::begin(), stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::end(), stxxl::is_sorted(), memory_to_use, stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::size(), stxxl::sort(), stxxl::stl_in_memory_sort(), and STXXL_MSG.
bool operator!= (const my_type & a, const my_type & b)
Definition at line 66 of file test_sort.cpp.
bool operator< (const my_type & a, const my_type & b)
Definition at line 56 of file test_sort.cpp.
std::ostream& operator<< (std::ostream & o, const my_type & obj)
Definition at line 50 of file test_sort.cpp.
bool operator== (const my_type & a, const my_type & b)
Definition at line 61 of file test_sort.cpp.