Stxxl: containers/tpie_stack_benchmark.cpp File Reference
containers/tpie_stack_benchmark.cpp File Reference
#include "app_config.h"
#include <portability.h>
#include <versions.h>
#include <ami_stack.h>
#include <ami_scan_utils.h>
#include <stxxl/bits/common/utils.h>
#include <stxxl/bits/verbose.h>
#include <stxxl/timer>
Defines
#define MEM_2_RESERVE (768 * 1024 * 1024)
#define BLOCK_SIZE (2 * 1024 * 1024)
#define DISKS 1
Functions
template<class my_record >
void run_stack (stxxl::int64 volume)
int main (int argc, char *argv[])
Define Documentation
#define BLOCK_SIZE (2 * 1024 * 1024)
Definition at line 39 of file tpie_stack_benchmark.cpp.
Referenced by run_stack().
#define DISKS 1
Definition at line 43 of file tpie_stack_benchmark.cpp.
Referenced by run_stack().
#define MEM_2_RESERVE (768 * 1024 * 1024)
Definition at line 37 of file tpie_stack_benchmark.cpp.
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
Definition at line 119 of file tpie_stack_benchmark.cpp.
References stxxl::atoint64(), BTE_STREAM_UFS_BLOCK_FACTOR, MEM_2_RESERVE, and STXXL_MSG.
template<class my_record > void run_stack (stxxl::int64 volume)
Definition at line 55 of file tpie_stack_benchmark.cpp.
References BLOCK_SIZE, DISKS, stxxl::timer::mseconds(), stxxl::timer::reset(), stxxl::timer::start(), stxxl::timer::stop(), and STXXL_MSG.