Stxxl: io/verify_disks.cpp File Reference
io/verify_disks.cpp File Reference
#include <iomanip>
#include <vector>
#include <stxxl/io>
#include <stxxl/aligned_alloc>
#include <stxxl/timer>
Defines
#define BLOCK_ALIGN 4096
#define POLL_DELAY 1000
#define RAW_ACCESS
#define MB (1024 * 1024)
#define GB (1024 * 1024 * 1024)
Functions
void usage (const char *argv0)
double throughput (double bytes, double seconds)
int main (int argc, char *argv[])
Define Documentation
#define BLOCK_ALIGN 4096
Definition at line 41 of file verify_disks.cpp.
#define GB (1024 * 1024 * 1024)
Definition at line 92 of file verify_disks.cpp.
Referenced by main().
#define MB (1024 * 1024)
Definition at line 91 of file verify_disks.cpp.
Referenced by main().
#define POLL_DELAY 1000
Definition at line 47 of file verify_disks.cpp.
#define RAW_ACCESS
Definition at line 49 of file verify_disks.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 119 of file verify_disks.cpp.
References block_size, stxxl::div_ceil(), GB, MB, stxxl::STXXL_MAX(), throughput(), stxxl::timestamp(), usage(), and stxxl::wait_all().
double throughput (double bytes, double seconds) [inline]
Definition at line 112 of file verify_disks.cpp.
void usage (const char * argv0)
Definition at line 94 of file verify_disks.cpp.