Stxxl: containers/write_vector.cpp File Reference
containers/write_vector.cpp File Reference
#include <stxxl/io>
#include <stxxl/vector>
#include <stxxl/bits/mng/buf_ostream.h>
Typedefs
typedef unsigned char my_type
Functions
int main (int argc, char *argv[])
Typedef Documentation
typedef unsigned char my_type
Definition at line 88 of file write_vector.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 95 of file write_vector.cpp.
References stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::begin(), stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::end(), and stxxl::vector< Tp_, PgSz_, PgTp_, BlkSize_, AllocStr_, SzTp_ >::size().