//
// File:  src/console/console.idl
//
// Description: Interface for the console server,
// Using IF_FILE
//

/* The console interface description */

/* our C++ datatypes and IDL4 datatypes  */
#include <types.idl>
#include <iffile.idl>

/*
 * Interface console inherits Interface IF_FILE.
 * Additionally it can receive interrupts.
 */
interface console: IF_FILE {
	
	[kernelmsg(idl4::interrupt)] void interrupt();
};
